### PR TITLE
Update Kafka + Avro quickstart to use Apicurio Registry 2.x

### PR DESCRIPTION
**Pull request by Ladicek**
**Check list**:

Your pull request:

- [x] targets the `development` branch
- [x] uses the `999-SNAPSHOT` version of Quarkus
- [x] has tests (`mvn clean test`)
- [x] works in native (`mvn clean package -Pnative`)
- [x] has native tests (`mvn clean verify -Pnative`)
- [ ] makes sure the associated guide must not be updated
    - what does this mean? of course the associated guide must be updated, see the item below!
- [x] links the guide update pull request (if needed)
    - https://github.com/quarkusio/quarkus/pull/16473
- [ ] updates or creates the `README.md` file (with build and run instructions)
- [ ] for new quickstart, is located in the directory _component-quickstart_
- [ ] for new quickstart, is added to the root `pom.xml` and `README.md`

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]
LGTM!

**Comment by cescoffier** [comment]
The test failure looks related.

**Comment by Ladicek** [comment]
I probably should have created this as a draft, because the native test can't pass until the Quarkus PR is merged. The present failure, though, isn't in the native test, but it's some weird NPE in the Kafka connector in SmallRye Reactive Messaging. I'll look into it a bit, but no promises :-)

Oh and I'll mark this as a draft for now.

**Comment by gsmet** [comment]
The Quarkus PR has been merged, let's restart CI.

**Comment by gsmet** [comment]
The tests still don't pass.

**Comment by Ladicek** [comment]
Thanks, I wanted to rebase and take a look today :-) Will check.

**Comment by Ladicek** [comment]
I forgot to include the `quarkus.test.flat-class-path=true` incantation :-) Let's see now.

**Comment by Ladicek** [comment]
The last failure is in `kafka-streams-quickstart-aggregator` and hence unrelated.

**Comment by gsmet** [comment]
Rebased to get the latest CI fixes. `quarkus.test.flat-class-path=true` should not be required soon, I'll remove it as soon as Stuart's PR is in.

**Pull request merged**
