### PR TITLE
Switch to dev services and resteasy reactive

### PR DESCRIPTION
**Pull request by cescoffier**
Also simplify the content a bit, as some annotations are not required anymore.

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Excellent!

**Comment by cescoffier** [comment]
CI failed because of graphql client changes.
@phillip-kruger is working on a fix. I will rebase once in.

**Comment by phillip-kruger** [comment]
Fix is here: https://github.com/quarkusio/quarkus-quickstarts/pull/886

**Comment by cescoffier** [comment]
Rebasing as the graphql fixed has been merged.

**Comment by cescoffier** [comment]
Merging, CI issue is unrelated.

**Pull request merged**
