### PR TITLE
Remove usages of deprecated native-image goal

### PR DESCRIPTION
**Pull request by jsmrcka**
Cherry-picked from https://github.com/quarkusio/quarkus-quickstarts/pull/765.

cc @rsvoboda

### CODE REVIEW

**Comment by gsmet** [comment]
Makes sense but... we miss CI here. I'm gonna add a commit to enable it.

**Comment by rsvoboda** [comment]
```
Error:  Failed to execute goal on project security-jwt-quickstart: Could not resolve dependencies for project 
org.acme:security-jwt-quickstart:jar:1.0.0-SNAPSHOT: Could not transfer artifact io.smallrye:smallrye-jwt:jar:2.4.1 from/to 
central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/io/smallrye
/smallrye-jwt/2.4.1/smallrye-jwt-2.4.1.jar: Connection reset -> [Help 1]
```

**Comment by rsvoboda** [comment]
Green now, ready for merge

**Comment by rsvoboda** [comment]
Green now, ready for merge

**Review by rsvoboda — APPROVED** [review]

**Pull request merged**
