### PR TITLE
Update Dockerfile.jvm

### PR DESCRIPTION
**Pull request by hurzelpurzel**
The Dockerfile didn't run with Kaniko on gitlab-ci. The separated chown did solve the problem.
I think Quarkus should be as compatible as possible and not only work with docker an builder.

**Check list**:

Your pull request:

- [ ] targets the `development` branch
- [ ] uses the `999-SNAPSHOT` version of Quarkus
- [ ] has tests (`mvn clean test`)
- [ ] works in native (`mvn clean package -Pnative`)
- [ ] has native tests (`mvn clean verify -Pnative`)
- [ ] makes sure the associated guide must not be updated
- [ ] links the guide update pull request (if needed)
- [ ] updates or creates the `README.md` file (with build and run instructions)
- [ ] for new quickstart, is located in the directory _component-quickstart_
- [ ] for new quickstart, is added to the root `pom.xml` and `README.md`

### CODE REVIEW

**Comment by cescoffier** [comment]
What's the error displayed by Kaniko?
The change looks good, but we would need to change the template used to generate the docker file.

**Comment by hurzelpurzel** [comment]
error building image: error building stage: failed to get files used from context: failed to get fileinfo for /builds/playground108/logproducer/target/quarkus-app/lib: lstat /builds/playground108/logproducer/target/quarkus-app/lib: no such file or directory

As far as I understood, the --chown flag was introduced with docker-ce version 17.09 (see: https://stackoverflow.com/questions/44766665/how-do-i-docker-copy-as-non-root). It might be the case, that some builder like kaniko or moby does not support it.

**Comment by cescoffier** [comment]
Looking at the issue, it seems to be a kaniko limitation. Hopefully, it will be fixed soon. 
Your approach works but introduces an additional layer, which, as the top layer, will be executed on every build. However, if there is no other choice, let's go for it.

**Comment by cescoffier** [comment]
The PR does not target the right branch, please update to use the `development` branch.

**Comment by hurzelpurzel** [comment]
switch to

**Pull request closed without merging**
