### PR TITLE
Bump surefire from 2.22.x to 3.0.0-M5

### PR DESCRIPTION
**Pull request by famod**
Sync with https://github.com/quarkusio/quarkus/pull/10081 and https://github.com/quarkusio/quarkus/pull/10315

cc @geoand

### CODE REVIEW

**Comment by geoand** [comment]
Nice, thanks!

But lets keep this out of `development` (i.e. lets keep the PR open) until Quarkus `1.6.0.Final` has been released so the change doesn't end up in 1.6 version quickstarts.

**Comment by famod** [comment]
Ah, damn impatience. 😆

Please ping me before merging this so that I can cover any new quickstarts that are added until then (if any).

**Comment by geoand** [comment]
Will do!

**Comment by famod** [comment]
1.6.0 popped up in master, so I rebased this and included the two new quickstarts. Should be good to merge now, no? (if CI is ok)

**Comment by geoand** [comment]
Yup!

**Comment by famod** [comment]
@gsmet Can you merge this please? I don't want to keep this up to date...

**Pull request merged**
