### PR TITLE
Simplify build pipeline

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by gsmet** [comment]
I'm not sure about this. @cescoffier had good reasons to use the external action as it installs OpenJDK and IIRC GitHub installs the Azul one.

**Comment by geoand** [comment]
Then I'd definitely like to hear them :)

**Comment by gsmet** [comment]
well, see the end of my sentence :)

We want our things to be tested with OpenJDK not the Azul one.

**Comment by geoand** [comment]
> well, see the end of my sentence :)
> 
> We want our things to be tested with OpenJDK not the Azul one.

That's it? I thought there was something more than that :P

IMHO I don't think that is a good enough reason to not use the simplified way of doing things. Azul is just a build of OpenJDK in any case

**Comment by gsmet** [comment]
Is there a way to use a matrix to make the JDK names variables? That would already simplify things while still using official OpenJDK builds.

**Comment by geoand** [comment]
I think so. Let me check

**Comment by cescoffier** [comment]
We want to test against openjdk, which is the most used. If you want azul, add another job.

And, yes, we could you matrix, bit didn’t find them very useful.

**Comment by geoand** [comment]
Let's see if my latest test works

**Comment by geoand** [comment]
I think this latest version I added makes sense

**Comment by cescoffier** [comment]
Ok for now, but it also avoids having the possibility to test with another impl like OpenJ9.

**Comment by geoand** [comment]
Sure, but we can always cross that boat when we get there :)

**Pull request merged**
