### PR TITLE
Migrate Security WebAuthn quickstart from Hibernate Reactive to Hibernate ORM

### PR DESCRIPTION
**Pull request by michalvavrik**
Related to: https://github.com/quarkusio/quarkus/issues/36438

Guide changes: https://github.com/quarkusio/quarkus/pull/38299

**Check list**:

Your pull request:

- [x] targets the `development` branch
- [x] uses the `999-SNAPSHOT` version of Quarkus
- [x] has tests (`mvn clean test`)
- [x] works in native (`mvn clean package -Pnative`)
- [x] has integration/native tests (`mvn clean verify -Pnative`)
- [x] makes sure the associated guide must not be updated
- [x] links the guide update pull request (if needed)
- [x] updates or creates the `README.md` file (with build and run instructions)
- [x] for new quickstart, is located in the directory _component-quickstart_
- [x] for new quickstart, is added to the root `pom.xml` and `README.md`

### CODE REVIEW

**Review by FroMage — APPROVED** [review]
This is fine, but I do wonder if we should not have two quickstarts, because turning this into a reactive style is not trivial.

**Comment by michalvavrik** [comment]
> This is fine, but I do wonder if we should not have two quickstarts, because turning this into a reactive style is not trivial.

I agree. Now - I kept the part you approved and added as copy & paste original quickstart (no code changes) as new module. The new module has postfix `-reactive` and its README says it is using Hibernate Reactive.

When this PR is merged, I'll link WebAuth guide with Reactive quickstart as well.

Thanks for suggestion

**Comment by michalvavrik** [comment]
or @FroMage can re-check changes, I'll leave on whoever have little time :-) Quarkus PR is merged so we need to sync them.

**Review by FroMage — APPROVED** [review]
Sounds great!

**Pull request merged**
