### PR TITLE
Update REST client quickstarts to use stage.code.quarkus.io instead of restcountries.eu

### PR DESCRIPTION
**Pull request by xstefank**
**Check list**:

Your pull request:

- [x] targets the `development` branch
- [x] uses the `999-SNAPSHOT` version of Quarkus
- [x] has tests (`mvn clean test`)
- [x] works in native (`mvn clean package -Pnative`)
- [x] has native tests (`mvn clean verify -Pnative`)
- [x] links the guide update pull request (if needed)
- [x] updates or creates the `README.md` file (with build and run instructions)

Associated guides docs updates - https://github.com/quarkusio/quarkus/pull/21166.

### CODE REVIEW

**Comment by michalszynkiewicz** [comment]
the failures are unrelated, they are in the s3 quickstart

**Comment by michalszynkiewicz** [comment]
Looks good to me.
@ia3andy would you also like to take a look at it (since it's using the code.quarkus API)?

**Comment by xstefank** [comment]
@michalszynkiewicz should be good because it's using just the new endpoint I've added last week.

**Comment by xstefank** [comment]
@michalszynkiewicz should I also squash this one?

**Pull request merged**
