### PR TITLE
Fix RSS regression CI action step failure

### PR DESCRIPTION
**Pull request by johnaohara**
This fixes the current failures in the RSS check  for the "Native Test - development" action

### CODE REVIEW

**Comment by geoand** [comment]
@gsmet any idea why CI is failing? I restarted it and still nothing. In any case, we should probably merge this and cherry-pick to master

**Comment by geoand** [comment]
@johnaohara can you try rebasing onto the latest `development` please?

**Comment by johnaohara** [comment]
@geoand have rebased, lets see if CI passes

**Comment by geoand** [comment]
CI is failing with: 

```
2020-03-26T14:17:40.3480529Z [ERROR] Plugin org.jacoco:jacoco-maven-plugin:0.8.4 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.jacoco:jacoco-maven-plugin:jar:0.8.4: Could not transfer artifact org.jacoco:jacoco-maven-plugin:pom:0.8.4 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/jacoco/jacoco-maven-plugin/0.8.4/jacoco-maven-plugin-0.8.4.pom: Connection timed out (Read failed) -> [Help 1]
```

I think we can merge anyway...

**Comment by geoand** [comment]
Thanks @johnaohara

**Pull request merged**
