### PR TITLE
Update infinispan-client-quickstart with tests relating to issue #147

### PR DESCRIPTION
**Pull request by mikrethor**
PR related to issue #147 

Tests added in native dans non native mode.

### CODE REVIEW

**Comment by mikrethor** [comment]
Should I also move the java version to 11 ?

**Comment by mikrethor** [comment]
What is the proper way to set the version of testcontainer ?

I used -Dquarkus-plugin.version=1.4.2.Final and -Dquarkus.platform.version=1.4.2.Final and it brought testcontainer properly.

**Comment by gsmet** [comment]
I rebased and squashed the commits, let's see how CI goes.

**Comment by mikrethor** [comment]
Seems fine merge?

**Comment by gsmet** [comment]
Yes, sorry for the delay and thanks for the PR!

**Comment by mikrethor** [comment]
You are welcome thanks for the work on Quarkus

**Pull request merged**
