### PR TITLE
Don't run grpc-tls-quickstart in cron as it fails with Java 8

### PR DESCRIPTION
**Pull request by geoand**
cc @cescoffier 

Can you please also cherry-pick this into `master`?

### CODE REVIEW

**Comment by geoand** [comment]
If you could cherry pick to master in order to make it available to GH actions, it would be great

**Comment by geoand** [comment]
@cescoffier or @gsmet If you could cherry pick this into `master`, that would be great

**Comment by cescoffier** [comment]
@geoand On it, sorry, late start this morning.

**Comment by geoand** [comment]
Thanks!

**Comment by cescoffier** [comment]
Done!

**Comment by geoand** [comment]
Excellent, thanks @cescoffier!

**Pull request merged**
