### PR TITLE
remove authz related class

### PR DESCRIPTION
**Pull request by sebastienblanc**
@pedroigor follow up on the guide change

### CODE REVIEW

**Comment by sberyozkin** [comment]
@sebastienblanc Why is it removed ?

**Comment by sebastienblanc** [comment]
Because authz is not part of quarkus-oidc anymore , it is now in
quarkus-keycloak-aurhorization

Le mar. 12 nov. 2019 à 18:31, sberyozkin <notifications@github.com> a
écrit :

**Comment by pedroigor** [comment]
@sberyozkin @sebastienblanc makes sense. But your commit is referencing the old directory name of the quickstart (`using-openid-connect`). Now the name is `security-openid-connect-quickstart`.

Shouldn't you also send the PR to the development branch too?

**Comment by sebastienblanc** [comment]
Yeah did it all wrong , will redo it probably tomorrow morning

Le mar. 12 nov. 2019 à 20:16, Pedro Igor <notifications@github.com> a
écrit :

**Comment by sberyozkin** [comment]
I see, thanks

**Pull request closed without merging**
