### PR TITLE
fix: change store type to `jdbc-cmt` because `db` will be deprecated

### PR DESCRIPTION
**Pull request by machi1990**
**Check list**:

Your pull request:

- [x] targets the `development` branch
- [x] uses the `999-SNAPSHOT` version of Quarkus
- [x] has tests (`mvn clean test`)
- [x] works in native (`mvn clean package -Pnative`)
- [x] has native tests (`mvn clean verify -Pnative`)
- [x] makes sure the documentation must not be updated
- [x] links the documentation update pull request (if needed)
- [x] updates or creates the `README.md` file (with build and run instructions)
- [x] For new quickstart, is located in the directory _component-quickstart_
- [x] For new quickstart, is added to the root `pom.xml` and `README.md`

To be merged after https://github.com/quarkusio/quarkus/pull/8566 

/cc @mkouba

### CODE REVIEW

**Comment by machi1990** [comment]
@gsmet we should also merge this one now that https://github.com/quarkusio/quarkus/pull/8566  is merged. It is a trivial change but it'd be good to have a clean CI run, the failure was because the enum value `jdbc-cmt` was not there yet. Can you re-run it? I do not have the rights. Thanks

**Comment by gsmet** [comment]
Rebased to trigger CI.

**Comment by machi1990** [comment]
Thanks @gsmet

**Comment by machi1990** [comment]
I thought there is an option to re-launch the build via the GH UI.

**Pull request merged**
