### PR TITLE
hibernate-search-standalone-elasticsearch-quickstart

### PR DESCRIPTION
**Pull request by yrodiere**
Relates to (and requires) https://github.com/quarkusio/quarkus/pull/39415

### CODE REVIEW

**Comment by yrodiere** [comment]
https://github.com/quarkusio/quarkus/pull/39415 was merged into main; restarting CI to check it works fine now, then we can merge.

**Comment by yrodiere** [comment]
Failures are unrelated; merging.

I'll look into the `hibernate-orm-multi-tenancy-quickstart` failure.

Hey @mkouba / @manovotn , do you think you could have a look at the quartz-quickstart failure? It seems to be failing on the `development` branch too, not just on this PR. See https://github.com/quarkusio/quarkus-quickstarts/actions/runs/8320248102/job/22764691285

**Comment by yrodiere** [comment]
> I'll look into the `hibernate-orm-multi-tenancy-quickstart` failure.

Someone is already on it: https://github.com/quarkusio/quarkus-quickstarts/pull/1398

**Comment by yrodiere** [comment]
> Hey @mkouba / @manovotn , do you think you could have a look at the quartz-quickstart failure? It seems to be failing on the `development` branch too, not just on this PR. See https://github.com/quarkusio/quarkus-quickstarts/actions/runs/8320248102/job/22764691285

And it looks like this will solve the quartz issue too: https://github.com/quarkusio/quarkus-quickstarts/pull/1398

Sorry for the noise :)

**Comment by gsmet** [comment]
Actually, this shouldn't have been merged before I branch the quickstarts for 3.9.

We don't have a branching mechanism for the quickstarts yet, we should probably have but it's low priority. I will have to revert it and it will need to be reapplied after 3.9 is branched.

(That's the reason why this PR was pending)

**Comment by yrodiere** [comment]
Damn, I really thought my PR got into 3.9... :disappointed:

**Pull request merged**
