### PR TITLE
Replace Debezium with Test Containers

### PR DESCRIPTION
**Pull request by cescoffier**

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Let's see what CI has to say.

**Comment by cescoffier** [comment]
We may hit the Avro classloading issue, let's see...

**Comment by gsmet** [comment]
Yeah but that's not an issue. I'll just check if the Kafka Streams test passes.

**Comment by gsmet** [comment]
Kafka Streams is now OK AFAICS. Merging.

**Pull request merged**
