### PR TITLE
Hibernate Reactive + Vert.x Web routing + Mutiny quickstart

### PR DESCRIPTION
**Pull request by DavideD**
This follows https://github.com/quarkusio/quarkus-quickstarts/pull/612
and I guess we shouldn't merge this until that one  is also merged.

I'm sending the PR anyway because I don't want to loose the branch on my repository.

### CODE REVIEW

**Comment by DavideD** [comment]
@gsmet, @Sanne

**Comment by gsmet** [comment]
@DavideD could you rebase now that the other PR is in? Thanks!

**Comment by DavideD** [comment]
Done

**Comment by DavideD** [comment]
Actually, I left a dependency that's not needed. 1 sec

**Comment by gsmet** [comment]
Yeah GH is all borked right now.

**Comment by Sanne** [comment]
Looks great ! Thanks

**Pull request merged**
