### PR TITLE
Spring Data REST quickstart

### PR DESCRIPTION
**Pull request by gytis**
cc @geoand

### CODE REVIEW

**Comment by gytis** [comment]
The extension PR https://github.com/quarkusio/quarkus/pull/13373

**Comment by geoand** [comment]
Let's relaunch CI when the extension is merged into the Quarkus repo

**Comment by gsmet** [comment]
Force pushed a rebase on top of latest `development` branch.

**Comment by gytis** [comment]
Seems that the database setup for the tests is wrong. I'll fix it.

**Review by aureamunoz — COMMENTED** [review]
I think that a DB should be automatically started started like [here](https://github.com/quarkusio/quarkus-quickstarts/blob/c494fc98c802787f3d3d77bd57314536ce8e6e3c/spring-data-jpa-quickstart/pom.xml#L91) @gytis

**Comment by gsmet** [comment]
@gytis don't forget to either pull the rebase or rebase it yourself as we had other issues.

**Comment by aureamunoz** [comment]
hahah, sorry @gytis I had not seen your comment when I add mine :-S

**Comment by gytis** [comment]
@gsmet fixed.

**Comment by gsmet** [comment]
OK, thanks!

**Pull request merged**
