### PR TITLE
Switch REST Client to extensions in 2.2

### PR DESCRIPTION
**Pull request by michalszynkiewicz**
originally by @xstefank

### CODE REVIEW

**Comment by gsmet** [comment]
I enabled CI for the 2.2 branch and force pushed to your branch. Let's see what CI has to say.

**Comment by gsmet** [comment]
And thanks for taking care of it :).

**Comment by xstefank** [comment]
btw for the future, feel free to ping me for backports too. I'm just not part of the quarkus triage so I don't know what needs to be ported :) Feel free to also include me in triage if you think it might be useful.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks.

**Comment by gsmet** [comment]
@xstefank tbh, we totally missed we would have to backport it.

**Pull request merged**
