### PR TITLE
Disable security-jwt-quickstart for now

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
cc @sberyozkin

**Comment by geoand** [comment]
Closing after getting input from @sberyozkin

**Comment by sberyozkin** [comment]
@geoand we should probably disable until https://github.com/quarkusio/quarkus/issues/8881 is fixed, do you agree ?

**Comment by geoand** [comment]
Should we merge this for now @sberyozkin ?

**Comment by geoand** [comment]
Ah sorry, just saw your comment :)

**Comment by sberyozkin** [comment]
Yeah, let me do it, thanks

**Comment by geoand** [comment]
Thanks @sberyozkin

**Comment by sberyozkin** [comment]
@geoand np, thanks for the PR

**Pull request merged**
