### PR TITLE
Update REST Assured version

### PR DESCRIPTION
**Pull request by Parthib314**
**Check list**:

Your pull request:

- [ ] targets the `development` branch
- [ ] uses the `999-SNAPSHOT` version of Quarkus
- [ ] has tests (`mvn clean test`)
- [ ] works in native (`mvn clean package -Pnative`)
- [ ] has integration/native tests (`mvn clean verify -Pnative`)
- [ ] makes sure the associated guide must not be updated
- [ ] links the guide update pull request (if needed)
- [ ] updates or creates the `README.md` file (with build and run instructions)
- [ ] for new quickstart, is located in the directory _component-quickstart_
- [ ] for new quickstart, is added to the root `pom.xml` and `README.md`

### CODE REVIEW

**Comment by gastaldi** [comment]
Please rebase this PR to contain only your commits (and preferably squash them in a single commit)

**Comment by gastaldi** [comment]
Also make sure the checklist in the PR comment is reflecting the actual behavior

**Comment by Parthib314** [comment]
> Please rebase this PR to contain only your commits (and preferably squash them in a single commit)

Done

**Review by gastaldi — CHANGES_REQUESTED** [review]
@Parthib314 sorry but this still doesn't look right. Your PR is touching 487 files which I believe does not belong to your change.

**Comment by Parthib314** [comment]
@gastaldi  Extremely sorry sir, I forked the main branch and made PR to the development branch so it compares all the changes between the main and development branch.

**Pull request closed without merging**
