### PR TITLE
Change package to reflect quarkus#5331

### PR DESCRIPTION
**Pull request by rsvoboda**
Change package to reflect https://github.com/quarkusio/quarkus/pull/5331

### CODE REVIEW

**Comment by sberyozkin** [comment]
@rsvoboda, @cescoffier   what about this commit, https://github.com/quarkusio/quarkus-quickstarts/pull/362 ? This one went to `master`, mine to `development`.

**Comment by cescoffier** [comment]
Damned! you are right.... 
Should we revert the change from master?

**Comment by sberyozkin** [comment]
@cescoffier I guess so :-)

**Comment by sberyozkin** [comment]
@cescoffier I can help if you are busy, just let me know

**Comment by cescoffier** [comment]
@sberyozkin That would be awesome!

**Comment by sberyozkin** [comment]
@cescoffier Hi Clement, you will probably spend more time answering my questions how to do it properly :-) (though may help me in the future), there are quite a few options, so, given:
```
b89cca3 (HEAD -> master, upstream/master) Merge pull request #365 from rsvoboda/security-openid-connect-web-authentication-quickstart.compile.fix
66a06b2 Change package to reflect quarkus#5331
191b61c Merge pull request #360 from rsvoboda/unused.imports
fb897e6 Unused imports removal
```

what command against the `upstream master` should be issued ? (not sure about the complete history loss vs keeping it, etc).

**Comment by cescoffier** [comment]
reverting 66a06b2 should be good enough.

**Comment by sberyozkin** [comment]
@cescoffier Getting "You're not authorized to push to this branch" :-), sorry

**Comment by cescoffier** [comment]
ah ah... only Guilaume and I are allowed. Can you open a PR?

**Comment by cescoffier** [comment]
(against master for once).

**Comment by sberyozkin** [comment]
Sure

**Pull request merged**
