### PR TITLE
Funqy Google Cloud Functions quickstart

### PR DESCRIPTION
**Pull request by loicmathieu**
**Check list**:

Your pull request:

- [x] targets the `development` branch
- [x] uses the `999-SNAPSHOT` version of Quarkus
- [ ] has tests (`mvn clean test`)
- [ ] works in native (`mvn clean package -Pnative`)
- [ ] has native tests (`mvn clean verify -Pnative`)
- [x] makes sure the documentation must not be updated
- [x] links the documentation update pull request (if needed)
- [x] updates or creates the `README.md` file (with build and run instructions)
- [x] For new quickstart, is located in the directory _component-quickstart_
- [x] For new quickstart, is added to the root `pom.xml` and `README.md`

### CODE REVIEW

**Comment by loicmathieu** [comment]
The related document PR is here: https://github.com/quarkusio/quarkus/pull/11298

**Comment by loicmathieu** [comment]
No tests and no native support for Google Cloud Functions.
If the PR #635 si merged first this one will need to be updated to avoid building it in native.
If not, I will update #635 to also avoid building the new quickstart.

**Comment by gsmet** [comment]
I disabled the native build. That being said, I wonder if we should instead remove the profile from the pom?

**Comment by loicmathieu** [comment]
@gsmet removing the profile will make the integration test builds again in native but without building the native image and executing the test twice right ?
If yes, this is way better as it allow to control from the extension the exclusion from native image compilation instead of maintaining a list of excluded projects ...

**Comment by gsmet** [comment]
No, if you remove the profile altogether, it won't run anything native and just run the tests in JVM mode (as long as there are no native tests, but I suppose we removed them, right?).

**Comment by loicmathieu** [comment]
OK, I'll give it a try, it should be better for both quickstarts and extensions build.

**Pull request merged**
