### PR TITLE
Amazon KMS + SES Quickstarts

### PR DESCRIPTION
**Pull request by gsmet**
**Check list**:

Your pull request:

- [ ] targets the `development` branch
- [ ] uses the `999-SNAPSHOT` version of Quarkus
- [ ] has tests (`mvn clean test`)
- [ ] works in native (`mvn clean package -Pnative`)
- [ ] has native tests (`mvn clean verify -Pnative`)
- [ ] makes sure the documentation must not be updated
- [ ] links the documentation update pull request (if needed)
- [ ] updates or creates the `README.md` file (with build and run instructions)
- [ ] For new quickstart, is located in the directory _component-quickstart_
- [ ] For new quickstart, is added to the root `pom.xml` and `README.md`

### CODE REVIEW

**Comment by gsmet** [comment]
@marcinczeczko looks like there's something wrong with it?

**Comment by gsmet** [comment]
I just took the last commit from your PR.

**Comment by gsmet** [comment]
The KMS quickstart contains test resources from SQS:
```
[ERROR] /home/runner/work/quarkus-quickstarts/quarkus-quickstarts/amazon-kms-quickstart/src/test/java/org/acme/sqs/SqsResource.java:[14,43] package software.amazon.awssdk.services.sqs does not exist
[ERROR] /home/runner/work/quarkus-quickstarts/quarkus-quickstarts/amazon-kms-quickstart/src/test/java/org/acme/sqs/SqsResource.java:[21,13] cannot find symbol
  symbol:   class SqsClient
  location: class org.acme.sqs.SqsResource
```

**Comment by gsmet** [comment]
```
├── src
│   ├── main
│   │   ├── docker
│   │   │   ├── Dockerfile.jvm
│   │   │   └── Dockerfile.native
│   │   ├── java
│   │   │   └── org
│   │   │       └── acme
│   │   │           └── kms
│   │   │               ├── QuarkusKmsAsyncResource.java
│   │   │               └── QuarkusKmsSyncResource.java
│   │   └── resources
│   │       └── application.properties
│   └── test
│       └── java
│           └── org
│               └── acme
│                   └── sqs
│                       ├── NativeSqsResourcesIT.java
│                       ├── SqsResource.java
│                       └── SqsResourcesTest.java
```

**Comment by marcinczeczko** [comment]
@gsmet A terrible sorry, looks like I screwed something rebasing locally too :P I recovered KMS test part, you can cherry pick it from here: https://github.com/marcinczeczko/quarkus-quickstarts/commit/a409483da5ea95f7a9fa16b305b547c5e5209cb8

**Comment by gsmet** [comment]
Thanks! Let's see what CI has to say.

**Comment by marcinczeczko** [comment]
@gsmet looks like ci likes it

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request merged**
