### PR TITLE
Feat/panache repository

### PR DESCRIPTION
**Pull request by loicmathieu**
Add repository example for Hibernate with Panache and MongoDB with Panache.

**Check list**:

Your pull request:

- [x] targets the `development` branch
- [x] uses the `999-SNAPSHOT` version of Quarkus
- [x] has tests (`mvn clean test`)
- [ ] works in native (`mvn clean package -Pnative`)
- [ ] has native tests (`mvn clean verify -Pnative`)
- [ ] makes sure the documentation must not be updated
- [ ] links the documentation update pull request (if needed)
- [ ] updates or creates the `README.md` file (with build and run instructions)
- [ ] For new quickstart, is located in the directory _component-quickstart_
- [ ] For new quickstart, is added to the root `pom.xml` and `README.md`

### CODE REVIEW

**Comment by loicmathieu** [comment]
@gsmet @FroMage @emmanuelbernard I added the same example as the entity version for the repository pattern.

**Comment by rsvoboda** [comment]
@loicmathieu needs rebase

**Comment by loicmathieu** [comment]
@rsvoboda rebase done.
I launch `mvn clean verify` before pushing, is it enougth to check the formatting or is there a specific maven command ?

**Comment by rsvoboda** [comment]
For formatting there is https://github.com/quarkusio/quarkus-quickstarts/pull/456

On your own you can do it now with following commans (just change path of eclipse-format.xml to reflect your directory structure)

 - mvn -Dproject.build.sourceEncoding=UTF-8 net.revelc.code.formatter:formatter-maven-plugin:2.11.0:format -Dconfigfile=/Users/rsvoboda/git/quarkus/ide-config/eclipse-format.xml
 - mvn -Dproject.build.sourceEncoding=UTF-8 net.revelc.code:impsort-maven-plugin:1.3.2:sort -Dimpsort.groups='java.,javax.,org.,com.' -Dimpsort.staticGroups='*' -Dimpsort.removeUnused=true

**Comment by loicmathieu** [comment]
@rsvoboda thanks, I reformat the new code, now it's OK :)

Maybe this information should be inside the CONTRIBUTING.md file of the quickstart (and on the PR checklist)

**Comment by loicmathieu** [comment]
@gsmet now that 1.3 is out with the new documentation for Panache covering both entity and repository at the same level, can we merge this PR that adds the repository implementation to the quickstarts ?

**Comment by loicmathieu** [comment]
@rsvoboda @gsmet I rebase this old PR and update the test.

Can we merge it ? It align the quickstarts with the changes made to the guide in Quarkus 1.3.

**Review by rsvoboda — APPROVED** [review]
I have no objections to the code changes

**Comment by loicmathieu** [comment]
@rsvoboda great! One thing from my todo list one year ago merged ;)

**Pull request merged**
