### PR TITLE
remove outdated getting-started-native

### PR DESCRIPTION
**Pull request by soul2zimate**
Remove getting-started-native directory after https://github.com/quarkusio/quarkus-quickstarts/pull/87

### CODE REVIEW

**Comment by vorburger** [comment]
@soul2zimate LGTM (same as my #114 for `getting-started-kubernetes`)

@cescoffier merge this?

**Comment by vorburger** [comment]
@geoand merge this?

**Comment by geoand** [comment]
Actually I am not sure if the PR is supposed to be against development... @cescoffier ?

**Comment by cescoffier** [comment]
No master should be good here as I will cherry pick it on development

**Pull request merged**
