### PR TITLE
(fix): simplify and improve knative quickstart

### PR DESCRIPTION
**Pull request by kameshsampath**
- using official quarks maven image
- added native test
- removed secret to pull from github
- added buildh based build script

Fixes: #112

Signed-off-by: Kamesh Sampath <kamesh.sampath@hotmail.com>

### CODE REVIEW

**Comment by kameshsampath** [comment]
FYI @cescoffier for review and merge

**Comment by starksm64** [comment]
I'm trying out the getting-started-knative-guide PR on this PR and when I try the first docker build step the image generation is failing with a 137 exit code:

```bash
Scotts-iMacPro:getting-started-knative starksm$ docker build -t starksm64/getting-started-knative .
Sending build context to Docker daemon    106kB
...
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] Running Quarkus native-image plugin on OpenJDK GraalVM CE 1.0.0-rc13
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] /opt/graalvm/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar quarkus-quickstart-knative-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http -H:-SpawnIsolates -H:-JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
[quarkus-quickstart-knative-runner:109]    classlist:   6,325.70 ms
[quarkus-quickstart-knative-runner:109]        (cap):  11,885.36 ms
[quarkus-quickstart-knative-runner:109]        setup:  30,578.42 ms
14:11:59,317 INFO  [org.xnio] XNIO version 3.7.0.Final
14:12:01,572 INFO  [org.xni.nio] XNIO NIO Implementation Version 3.7.0.Final
Error: Image building with exit status 137
```

**Comment by kameshsampath** [comment]
@starksm64  I just now built it from the branch and my build as successful. When i searched a bit it says return code 137 is because of some memory error. Wondering whats the docker you using? Did you check the memory limit of it ?

**Comment by starksm64** [comment]
It's the docker desktop. Checking its settings shows it was at 2G. I upped it to 12G and the build ran, but ended with a message about not being able to pull from registry.fedoraproject.org, and then the next step of the docker push fails:

```bash
Step 4/8 : FROM registry.fedoraproject.org
pull access denied for registry.fedoraproject.org, repository does not exist or may require 'docker login'
Scotts-iMacPro:getting-started-knative starksm$ docker push starksm64/getting-started-knative
The push refers to repository [docker.io/starksm64/getting-started-knative]
An image does not exist locally with the tag: starksm64/getting-started-knative
```

**Comment by kameshsampath** [comment]
@cescoffier - this has been updated can you please merge. It will be great if you can merge https://github.com/quarkusio/quarkus-images/pull/6

**Pull request closed without merging**
