### PR TITLE
Replace removed io.quarkus.qute.api.CheckedTemplate annotation

### PR DESCRIPTION
**Pull request by kshpak**
Breaking change introduced by pull request 16468 in quarkusio/quarkus

**Check list**:

Your pull request:

- [ *] uses the `999-SNAPSHOT` version of Quarkus
- [ *] works in native (`mvn clean package -Pnative`)

### CODE REVIEW

**Review by mkouba — APPROVED** [review]

**Comment by rsvoboda** [comment]
@kshpak tried to change the base but it pulls release commits from the main.

PRs need to be based on `development` branch and filed against it.

Please update your branch to reflect ^^^ or if struggling please close this PR and create new one.

**Comment by kshpak** [comment]
PR changed to hit development branch

**Comment by rsvoboda** [comment]
Kafka streams fails with:
```
 Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.203 s <<< FAILURE! - in org.acme.kafka.streams.aggregator.streams.TopologyProducerTest
Error:  org.acme.kafka.streams.aggregator.streams.TopologyProducerTest.test  Time elapsed: 0.007 s  <<< ERROR!
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.RuntimeException: Error waiting for test resource future to finish.
Caused by: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/codahale/metrics/Reservoir
Caused by: java.lang.NoClassDefFoundError: com/codahale/metrics/Reservoir
Caused by: java.lang.ClassNotFoundException: com.codahale.metrics.Reservoir
```

Not related to this PR change.

**Comment by rsvoboda** [comment]
@cescoffier / @gunnarmorling are you aware of `java.lang.NoClassDefFoundError: com/codahale/metrics/Reservoir` issue with latest Quarkus main? (see the above comment)

**Review by rsvoboda — APPROVED** [review]

**Comment by cescoffier** [comment]
@rsvoboda @gsmet introduced this bug :-D I had a look at it yesterday, it's an issue with the new Zookeeper. 

@gsmet do you want me to add the missing dependency?

**Comment by gsmet** [comment]
I'll have a look next week (probably).

**Pull request merged**
