### PR TITLE
[DO NOT MERGE] getting-started - Change native image tests to use `@QuarkusIntegrationTest`

### PR DESCRIPTION
**Pull request by edeandrea**
This requires quarkusio/quarkus#23488 to be merged.

That PR changes the way code is generated. The native test using `@NativeImageTest` is changed to use `@QuarkusintegrationTest` instead.

**Check list**:

Your pull request:

- [X] targets the `development` branch
- [X] uses the `999-SNAPSHOT` version of Quarkus
- [X] has tests (`mvn clean test`)
- [X] works in native (`mvn clean package -Pnative`)
- [X] has native tests (`mvn clean verify -Pnative`)
- [X] makes sure the associated guide must not be updated
- [X] links the guide update pull request (if needed)
- [X] updates or creates the `README.md` file (with build and run instructions)

### CODE REVIEW

**Comment by edeandrea** [comment]
One question I had though is **Should all the quickstarts be updated to use this pattern?** If so, I can add that before merging.

**Comment by edeandrea** [comment]
@geoand should this wait until quarkusio/quarkus#23488 is released?

Also I only updated the getting started, but should all the tests that use `@NativeImageTest` be updated?

**Comment by geoand** [comment]
> @geoand should this wait until https://github.com/quarkusio/quarkus/pull/23488 is released?

Nah, we can do it now.

> Also I only updated the getting started, but should all the tests that use @NativeImageTest be updated?

Yeah, we should do it for all

**Comment by geoand** [comment]
Done :)

**Comment by edeandrea** [comment]
Crap I made the mistake of rebasing this from `main` and not `development`. @geoand do you know any git-fu where I can back out a rebase?

If not I can close this and open a new one....

**Comment by edeandrea** [comment]
Alright I'll close this one in favor of a new one once I finish everything up.

**Pull request closed without merging**
