### PR TITLE
Avoid building GCF native image

### PR DESCRIPTION
**Pull request by loicmathieu**
**Check list**:

Your pull request:

- [x] targets the `development` branch
- [x] uses the `999-SNAPSHOT` version of Quarkus
- [ ] has tests (`mvn clean test`)
- [ ] works in native (`mvn clean package -Pnative`)
- [ ] has native tests (`mvn clean verify -Pnative`)
- [x] makes sure the documentation must not be updated
- [ ] links the documentation update pull request (if needed)
- [ ] updates or creates the `README.md` file (with build and run instructions)
- [ ] For new quickstart, is located in the directory _component-quickstart_
- [ ] For new quickstart, is added to the root `pom.xml` and `README.md`

### CODE REVIEW

**Comment by loicmathieu** [comment]
@geoand the build fails on the gradle quickstarts.
I don't know if we can merge it nevertheless or if we should try to fix the build?

**Comment by geoand** [comment]
@gsmet you wanted the quickstarts to fail in Gradle? Now they are :)

**Comment by loicmathieu** [comment]
@geoand I update my PR to also avoid native builds for the newly merged google-cloud-functions-http quickstart.

**Comment by geoand** [comment]
Great thanks! @gsmet can you please merge when this goes green and then cherry pick to master?

Thanks

**Pull request merged**
