### PR TITLE
Use the RESTEasy *Param annotations

### PR DESCRIPTION
**Pull request by FroMage**
I'll open a guide PR to update them too if you agree with this change.

@cescoffier this can wait until after today's release, but can you fire up CI for this PR? It passes locally…

### CODE REVIEW

**Comment by FroMage** [comment]
@gsmet this can wait until after today's release.

**Comment by gsmet** [comment]
There is a conflict. The `getting-started/build.gradle` file was removed as we need a separate Gradle project with a Gradle-like file organization.

Can you drop this part of the change and ping me when it's done?

Thanks!

**Comment by FroMage** [comment]
Done.

**Comment by gsmet** [comment]
Thanks!

**Pull request merged**
