### PR TITLE
Revert enforcing antlr4.9

### PR DESCRIPTION
**Pull request by radtriste**
Reverts:
- https://github.com/quarkusio/quarkus-quickstarts/pull/1155
- https://github.com/quarkusio/quarkus-quickstarts/pull/1213

Drools / Kogito is now using Antlr 4.10.1

**Check list**:

Your pull request:

- [x] targets the `development` branch
- [ ] uses the `999-SNAPSHOT` version of Quarkus
- [ ] has tests (`mvn clean test`)
- [ ] works in native (`mvn clean package -Pnative`)
- [ ] has integration/native tests (`mvn clean verify -Pnative`)
- [ ] makes sure the associated guide must not be updated
- [ ] links the guide update pull request (if needed)
- [ ] updates or creates the `README.md` file (with build and run instructions)
- [ ] for new quickstart, is located in the directory _component-quickstart_
- [ ] for new quickstart, is added to the root `pom.xml` and `README.md`

### CODE REVIEW

**Comment by radtriste** [comment]
@Sanne @tarilabs

**Review by gsmet — CHANGES_REQUESTED** [review]
I think you should update the Kogito versions in the POM files as we don't use the Platform here (chicken and egg issue).

**Comment by radtriste** [comment]
Gonna change that !

**Comment by radtriste** [comment]
@gsmet just noticed in quickstart we are still using version 1.24 ...
I guess some automation is needed there ...

**Comment by radtriste** [comment]
cc @cristianonicolai FYI

**Comment by gsmet** [comment]
Yes they are manually updated from time to time.
Could you also take care of Optaplanner while you're at it: https://github.com/quarkusio/quarkus-quickstarts/blob/main/optaplanner-quickstart/pom.xml#L13 ? That way we will have a complete PR for reference.

**Comment by radtriste** [comment]
oki
need also to check it is still working :)

**Pull request closed without merging**
