### PR TITLE
issue 717: Include a JTA quickstart

### PR DESCRIPTION
**Pull request by mmusgrov**
https://github.com/quarkusio/quarkus-quickstarts/issues/717

### CODE REVIEW

**Comment by mmusgrov** [comment]
@gsmet should I ping someone to get this reviewed or is it a case of waiting until the backlog is reduced?

**Comment by mmusgrov** [comment]
I pushed an update to the README to remove the comment about annoying error messages in native mode (the narayana-jta extension issue, #10180, that I mentioned in the README has been fixed and merged).

**Comment by AlbertLacambraNexplore** [comment]
Why is that not being merged?

**Comment by mmusgrov** [comment]
That's a very good question @AlbertLacambraNexplore - I forgot about this one as well. I thought it useful so would have expected others to have found it useful too.

**Comment by mmusgrov** [comment]
@AlbertLacambraNexplore I've just noticed that the PR hasn't been reviewed. Would it be possible for you to review it?

**Comment by gsmet** [comment]
I rebased on top of development as it needs to be pushed to this branch. Let's see what CI has to say now that it will get triggered.

**Comment by mmusgrov** [comment]
Thanks @gsmet

**Comment by gsmet** [comment]
CI failed when saving the cache but the build passed. Merging. Thanks and sorry for the delay.

**Comment by mmusgrov** [comment]
Thanks @gsmet

**Comment by AlbertLacambraNexplore** [comment]
I think I was too late for the review. Anyway, it looks good to me :)

**Pull request merged**
