### PR TITLE
Fix mongodb test

### PR DESCRIPTION
**Pull request by loicmathieu**
**Check list**:

Your pull request:

- [ ] targets the `development` branch
- [ ] uses the `999-SNAPSHOT` version of Quarkus
- [ ] has tests (`mvn clean test`)
- [ ] works in native (`mvn clean package -Pnative`)
- [ ] has native tests (`mvn clean verify -Pnative`)
- [ ] makes sure the associated guide must not be updated
- [ ] links the guide update pull request (if needed)
- [ ] updates or creates the `README.md` file (with build and run instructions)
- [ ] for new quickstart, is located in the directory _component-quickstart_
- [ ] for new quickstart, is added to the root `pom.xml` and `README.md`

### CODE REVIEW

**Comment by loicmathieu** [comment]
/cc @geoand 

Fixes the current CI issue for MongoDB with Panache

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Thanks!

**Comment by rsvoboda** [comment]
@loicmathieu what change in Quarkus master caused this change? I was just looking into mongodb-panache-quickstart fail.

**Comment by loicmathieu** [comment]
@rsvoboda accessors rewritting as exist for Hibernate with Panache has been implemented, so now person.name was rewritten to person.getName() inside the Panache processor and the test fail.

**Comment by rsvoboda** [comment]
ok, so https://github.com/quarkusio/quarkus-quickstarts/blob/master/mongodb-panache-quickstart/src/main/java/org/acme/mongodb/panache/Person.java#L23-L25 is called now, instead of getting the direct property value.

Should be a note about this change of behavior added into https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.11?

**Comment by loicmathieu** [comment]
@evanchooly the just merged field accessor rewritting you implemented for MongoDB with Panache can cause some bugs on existing code where getters/setters exists but developer still use the field directly. This was the case on the quickstart.

As @rsvoboda suggested, maybe it'll be a good idea to add a note about it inside the migration guide for 1.11

**Comment by evanchooly** [comment]
wouldn't a simple rebuild fix this?  I can certainly add a note to that effect but I'm a little surprised it broke a test since rebuilding them should have updated the bytecode accordingly.  What did the breakage look like?

**Comment by loicmathieu** [comment]
There was a lowercase on the getter, previously it was not used, now it is.

**Comment by evanchooly** [comment]
oh!  i see.  That entity had hand crafted a getter which was bypassed with field access.  Got it.  That was the missing piece for me.

**Pull request merged**
