### PR TITLE
Add CDI and rest client to opentracing example

### PR DESCRIPTION
**Pull request by pavolloffay**
Related to https://issues.jboss.org/browse/TRACING-461

Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by cescoffier** [comment]
@pavolloffay does it require anything from the Quarkus master branch? 

The question is whether or not this can be included in 0.13.2 (I would love to demonstrate this during the deep dive).

**Comment by pavolloffay** [comment]
This does not require anything from the master branch. 

The cool example for demo is also using fault tolerance and CDI/rest client. This PR https://github.com/quarkusio/quarkus/pull/2038 will add support for propagating spans inside FT.

**Comment by pavolloffay** [comment]
@gsmet can this be merged?

**Comment by gsmet** [comment]
@pavolloffay FYI, I haven't forgotten about this. I worked on https://github.com/quarkusio/quarkus/pull/2239 to fix the native image issues. For me, it's the condition before we can think about merging this one.

Unfortunately, I stumbled upon what looks like a GraalVM bug and we still have some errors/unwanted outputs, even with my fix.

I opened https://github.com/oracle/graal/issues/1200 .

**Comment by pavolloffay** [comment]
@gsmet should I also update the web page?

**Comment by gsmet** [comment]
@pavolloffay you're talking about the guide?

If so, yes, it's in the main repo here: https://github.com/quarkusio/quarkus/tree/master/docs/src/main/asciidoc .

**Comment by pavolloffay** [comment]
I had a quick look there. The sources contain more stuff than guide but I think it's fine. The most important stuff is there

**Pull request merged**
