### PR TITLE
Rename vertx-web to reactive-routes

### PR DESCRIPTION
**Pull request by loicmathieu**
**Check list**:

Your pull request:

- [ ] targets the `development` branch
- [ ] uses the `999-SNAPSHOT` version of Quarkus
- [ ] has tests (`mvn clean test`)
- [ ] works in native (`mvn clean package -Pnative`)
- [ ] has native tests (`mvn clean verify -Pnative`)
- [ ] makes sure the associated guide must not be updated
- [ ] links the guide update pull request (if needed)
- [ ] updates or creates the `README.md` file (with build and run instructions)
- [ ] for new quickstart, is located in the directory _component-quickstart_
- [ ] for new quickstart, is added to the root `pom.xml` and `README.md`

### CODE REVIEW

**Comment by loicmathieu** [comment]
/cc @geoand 
To be 100% sure I took the time to build it and deploy it to GCP. Still works :)

**Review by geoand — APPROVED** [review]
Thanks a lot!

**Comment by loicmathieu** [comment]
@geoand there was a little more quickstarts than the GCF one that contains the renamed dependencies.
I updated the three that I found.

**Comment by geoand** [comment]
Wonderful, 🙏

**Pull request merged**
