### PR TITLE
Extension guide

### PR DESCRIPTION
**Pull request by danielpetisme**
**Check list**:

Your pull request:

- [x] targets the `development` branch
- [x] uses the `999-SNAPSHOT` version of Quarkus
- [x] has tests (`mvn clean test`)
- [ ] works in native (`mvn clean package -Pnative`)
- [ ] has native tests (`mvn clean verify -Pnative`)
- [ ] makes sure the documentation must not be updated
- [ ] links the documentation update pull request (if needed)
- [ ] updates or creates the `README.md` file (with build and run instructions)
- [ ] For new quickstart, is located in the directory _component-quickstart_
- [ ] For new quickstart, is added to the root `pom.xml` and `README.md`

### CODE REVIEW

**Comment by danielpetisme** [comment]
When running tests, the extension tests are ignored...
```
mvn clean test

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.acme.quarkus.greeting.deployment.GreetingTest
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Greeting Extension - Parent 1.0-SNAPSHOT:
[INFO]
[INFO] Greeting Extension - Parent ........................ SUCCESS [  0.081 s]
[INFO] Greeting Extension - Runtime ....................... SUCCESS [  1.044 s]
[INFO] Greeting Extension - Deployment .................... SUCCESS [  1.253 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.479 s
[INFO] Finished at: 2019-12-13T23:30:02+01:00
[INFO] ------------------------------------------------------------------------
```

The weird thing is, if I add the `teste prefix to the test method (ie. `shouldGreet()` -> `testshouldGreet`()) the test is detected (and fail)...

If anyone has any clue, 🤔

**Comment by danielpetisme** [comment]
Thanks to @cescoffier I succeed to move on:
1- I need to explicitly define surefire version to not fallback to JUnit 4 legacy mode
2- Relying on `999-SNAPSHOT` (build with https://github.com/quarkusio/quarkus/commit/4c5d8fc33ac8e8299ffab577cda4ef6e7d6b7174) introduces different issues
  1- surefire `3.0.0-M4` does not detect the tests
  2- When using M3 the test produces an error
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.069 s <<< FAILURE! - in org.acme.quarkus.greeting.deployment.GreetingTest
[ERROR] org.acme.quarkus.greeting.deployment.GreetingTest  Time elapsed: 0.068 s  <<< ERROR!
java.lang.NoClassDefFoundError: io/quarkus/runner/RuntimeRunner
Caused by: java.lang.ClassNotFoundException: io.quarkus.runner.RuntimeRunner

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   GreetingTest » NoClassDefFound io/quarkus/runner/RuntimeRunner
```

To workaround the problem, I relied on `1.2.0.Final` and surefire `M4` and the tests pass properly
@gsmet Is it ok to stick with `1.2.0.Final` for a short period of time?

**Comment by rsvoboda** [comment]
@danielpetisme needs rebase

**Comment by gsmet** [comment]
Superseded by https://github.com/quarkusio/quarkus-quickstarts/pull/584 .

**Pull request closed without merging**
