### PR TITLE
Update Kogito to new version properly supporting recent Quarkus versions

### LINKED ISSUE #799: kogito-quickstart not working?
This looks like a problem w/ the module (quarkus-kogito) itself. 

When I POST a new Person, I get the results back in the response, however if I run a GET /persons immediately after, it's empty. 

I bumped up the quarkus logs to ALL, and I found something interesting when I do my POST: 

As far as I can tell, the last thing it's trying to do is delete the element I just posted. 

`2021-03-02 16:47:41,251 TRACE [org.dro.cor.phr.AddRemoveRule] (executor-thread-199) Adding Rule Is adult
2021-03-02 16:47:41,272 TRACE [org.dro.cor.ret.EntryPointNode] (executor-thread-199) Insert [fact 0:1:308758892:308758892:1:DEFAULT:NON_TRAIT:org.acme.kogito.model.Person:Person [name=John Doe, age=41, adult=false]]
2021-03-02 16:47:41,274 DEBUG [org.dro.cor.com.DefaultAgenda] (executor-thread-199) State was INACTIVE is now FIRING_ALL_RULES
2021-03-02 16:47:41,274 TRACE [org.dro.cor.com.DefaultAgenda] (executor-thread-199) Starting Fire All Rules
2021-03-02 16:47:41,277 TRACE [org.dro.cor.ret.PathMemory] (executor-thread-199)  LinkRule name=Is adult
2021-03-02 16:47:41,278 TRACE [org.dro.cor.ret.PathMemory] (executor-thread-199) Queue RuleAgendaItem [Activation rule=Is adult, act#=0, salience=0, tuple=null]
2021-03-02 16:47:41,278 TRACE [org.dro.cor.uti.BinaryHeapQueue] (executor-thread-199) Queue Added 1 [Activation rule=Is adult, act#=0, salience=0, tuple=null]
2021-03-02 16:47:41,284 TRACE [org.dro.cor.phr.RuleExecutor] (executor-thread-199) Fire event default for rule "Is adult" 
[[ Is adult active=false ] [ [fact 0:1:308758892:308758892:1:DEFAULT:NON_TRAIT:org.acme.kogito.model.Person:Person [name=John Doe, age=41, adult=false]] ] ]
2021-03-02 16:47:41,285 TRACE [org.dro.cor.ret.EntryPointNode] (executor-thread-199) Update [fact 0:1:308758892:308758892:2:DEFAULT:NON_TRAIT:org.acme.kogito.model.Person:Person [name=John Doe, age=41, adult=true]]
2021-03-02 16:47:41,286 TRACE [org.dro.cor.ret.PathMemory] (executor-thread-199)  LinkRule name=Is adult
2021-03-02 16:47:41,287 TRACE [org.dro.cor.phr.RuleExecutor] (executor-thread-199) Removing RuleAgendaItem [Activation rule=Is adult, act#=0, salience=0, tuple=null]
2021-03-02 16:47:41,287 TRACE [org.dro.cor.uti.BinaryHeapQueue] (executor-thread-199) Queue Removed 1 [Activation rule=Is adult, act#=0, salience=0, tuple=null]
2021-03-02 16:47:41,287 DEBUG [org.dro.cor.com.DefaultAgenda] (executor-thread-199) State was FIRING_ALL_RULES is now HALTING
2021-03-02 16:47:41,287 DEBUG [org.dro.cor.com.DefaultAgenda] (executor-thread-199) State was HALTING is now INACTIVE
2021-03-02 16:47:41,287 TRACE [org.dro.cor.com.DefaultAgenda] (executor-thread-199) Ending Fire All Rules
2021-03-02 16:47:41,288 TRACE [org.dro.cor.ret.EntryPointNode] (executor-thread-199) Delete [fact 0:1:308758892:308758892:2:DEFAULT:NON_TRAIT:org.acme.kogito.model.Person:Person [name=John Doe, age=41, adult=true]]
`

Regardless, if I try to exec a GET immediately after, I get an empty set.... [ ]
LOGS: 
2021-03-02 16:48:56,403 FINEST [io.ver.ext.web.imp.RouterImpl] (vert.x-eventloop-thread-28) Router: 86309173 accepting request GET http://localhost:8080/persons
2021-03-02 16:48:56,403 FINEST [io.ver.ext.web.imp.RoutingContextImplBase] (vert.x-eventloop-thread-28) Route matches: RouteState{path='null', order=-2147483648, enabled=true, methods=null, consumes=null, emptyBodyPermittedWithConsumes=false, produces=null, contextHandlers=[io.quarkus.vertx.http.runtime.VertxHttpRecorder$5@4cfe5b46], failureHandlers=null, added=true, pattern=null, groups=null, useNormalisedPath=true, namedGroupsInRegex=null, virtualHostPattern=null, pathEndsWithSlash=false, exclusive=false, exactPath=false}
2021-03-02 16:48:56,403 FINEST [io.ver.ext.web.imp.RoutingContextImplBase] (vert.x-eventloop-thread-28) Calling the  handler
2021-03-02 16:48:56,407 FINEST [io.ver.ext.web.imp.RoutingContextImplBase] (vert.x-eventloop-thread-28) Route matches: RouteState{path='null', order=-2, enabled=true, methods=null, consumes=null, emptyBodyPermittedWithConsumes=false, produces=null, contextHandlers=[io.quarkus.vertx.http.runtime.VertxHttpRecorder$4@58589238], failureHandlers=null, added=true, pattern=null, groups=null, useNormalisedPath=true, namedGroupsInRegex=null, virtualHostPattern=null, pathEndsWithSlash=false, exclusive=false, exactPath=false}
2021-03-02 16:48:56,407 FINEST [io.ver.ext.web.imp.RoutingContextImplBase] (vert.x-eventloop-thread-28) Calling the  handler
2021-03-02 16:48:56,407 FINEST [io.ver.ext.web.imp.RoutingContextImplBase] (vert.x-eventloop-thread-28) Route matches: RouteState{path='/', order=10001, enabled=true, methods=null, consumes=null, emptyBodyPermittedWithConsumes=false, produces=null, contextHandlers=[io.quarkus.resteasy.runtime.standalone.VertxRequestHandler@6b8e13a9], failureHandlers=null, added=true, pattern=null, groups=null, useNormalisedPath=true, namedGroupsInRegex=null, virtualHostPattern=null, pathEndsWithSlash=true, exclusive=false, exactPath=false}
2021-03-02 16:48:56,407 FINEST [io.ver.ext.web.imp.RoutingContextImplBase] (vert.x-eventloop-thread-28) Calling the  handler
2021-03-02 16:48:56,407 DEBUG [org.jbo.res.res.i18n] (executor-thread-199) RESTEASY002315: PathInfo: /persons
2021-03-02 16:48:56,410 DEBUG [org.jbo.res.res.i18n] (executor-thread-199) MessageBodyWriter: org.jboss.resteasy.core.providerfactory.SortedKey
2021-03-02 16:48:56,411 DEBUG [org.jbo.res.res.i18n] (executor-thread-199) MessageBodyWriter: org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider
2021-03-02 16:48:56,411 DEBUG [org.jbo.res.res.i18n] (executor-thread-199) MessageBodyWriter: org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider
2021-03-02 16:48:56,411 DEBUG [org.jbo.res.res.i18n] (executor-thread-199) MessageBodyWriter: org.jboss.resteasy.core.providerfactory.SortedKey
2021-03-02 16:48:56,411 DEBUG [org.jbo.res.res.i18n] (executor-thread-199) Interceptor Context: org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext,  Method : proceed
2021-03-02 16:48:56,412 DEBUG [org.jbo.res.res.i18n] (executor-thread-199) MessageBodyWriter: org.jboss.resteasy.core.providerfactory.SortedKey
2021-03-02 16:48:56,412 DEBUG [org.jbo.res.res.i18n] (executor-thread-199) MessageBodyWriter: org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider
2021-03-02 16:48:56,412 DEBUG [org.jbo.res.res.i18n] (executor-thread-199) Provider : org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider,  Method : writeTo

I hopped over to the kogito examples and i'm not having a problem. I'll take a closer look. My guess is version.

### PR DESCRIPTION
**Pull request by edtbl76**
**Check list**:

Your pull request:

- [X] targets the `development` branch
- [X] uses the `999-SNAPSHOT` version of Quarkus
- [X] has tests (`mvn clean test`)
- [X] works in native (`mvn clean package -Pnative`)
- [X] has native tests (`mvn clean verify -Pnative`)
- [X] makes sure the associated guide must not be updated
- [X] links the guide update pull request (if needed)
- [X] updates or creates the `README.md` file (with build and run instructions)
- [X] for new quickstart, is located in the directory _component-quickstart_
- [X] for new quickstart, is added to the root `pom.xml` and `README.md`

Fixes #799

### CODE REVIEW

**Comment by gsmet** [comment]
@edtbl76 I adjusted the PR to only include the Kogito change. I'll wait for CI to be green and merge. Thanks!

**Comment by edtbl76** [comment]
Awesome! Thanks for putting this stuff together. It’s a big help. I reduced
the other PR to minor stuff, no Lombok ;)


On March 3, 2021 at 8:42:38 AM, Guillaume Smet (notifications@github.com)
wrote:

@edtbl76 <https://github.com/edtbl76> I adjusted the PR to only include the
Kogito change. I'll wait for CI to be green and merge. Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/quarkusio/quarkus-quickstarts/pull/801#issuecomment-789722346>,
or unsubscribe

**Comment by gsmet** [comment]
Rebased to get an unrelated CI fix.

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request merged**
