### PR TITLE
switch grpc to use code-gen

### PR DESCRIPTION
**Pull request by michalszynkiewicz**
**Check list**:

Your pull request:

- [x] targets the `development` branch
- [x] uses the `999-SNAPSHOT` version of Quarkus
- [x] has tests (`mvn clean test`)
- [x] works in native (`mvn clean package -Pnative`)
- [x] has native tests (`mvn clean verify -Pnative`)
- [x] makes sure the associated guide must not be updated
- [ ] links the guide update pull request (if needed)
- [ ] updates or creates the `README.md` file (with build and run instructions)
- [ ] for new quickstart, is located in the directory _component-quickstart_
- [ ] for new quickstart, is added to the root `pom.xml` and `README.md`

### CODE REVIEW

**Comment by michalszynkiewicz** [comment]
this needs to be backported to 1.7

**Review by geoand — APPROVED** [review]

**Comment by michalszynkiewicz** [comment]
checked locally with -Dnative -Dquarkus.native.container-runtime=docker

**Review by cescoffier — APPROVED** [review]

**Comment by rsvoboda** [comment]
@geoand looking at https://github.com/quarkusio/quarkus-quickstarts/compare/1.7.3.Final...1.7.4.Final and this PR wasn't picked

Can you please create 1.7.5.Final tag with this change?

@gsmet fyi

**Comment by geoand** [comment]
@gsmet I see you haven't created the `1.7.5.Final`, should I proceed to do it after cherry-picking this?

**Pull request merged**
