### PR TITLE
Switch from elasticearch-maven-plugin to docker-maven-plugin to start Elasticsearch for ITs

### PR DESCRIPTION
**Pull request by yrodiere**
This is based on PR #636 , which should be merged first.

cc @gsmet 

Related to https://github.com/quarkusio/quarkus/pull/11599

### CODE REVIEW

**Comment by yrodiere** [comment]
The build failure is unrelated.

@Sanne could you please merge this, since you merged the similar change in Quarkus proper?

**Comment by yrodiere** [comment]
Note that this is based on #636 , but that one should be merged too (since the build is broken without it)

**Comment by Sanne** [comment]
I'm going to try this one now, but I'm having issues with docker locally so I might not be the best person to check it out

**Review by Sanne — APPROVED** [review]
Seems to work fine; one minor polishing: the README is suggestin docker commands to run ES, but the version of this ES server hasn't been updated.

I'll merge, I'll let you decide if it's important to follow up?

**Comment by Sanne** [comment]
hum, probably unrelated but I noticed now an error on stopping the demo:

```
2020-08-28 10:49:35,359 ERROR [io.qua.arc.imp.InstanceHandleImpl] (main) Error occurred while destroying instance of bean [io.quarkus.hibernate.orm.runtime.JPAConfig_Bean]: java.lang.UnsupportedOperationException
```

**Comment by yrodiere** [comment]
> I'll merge, I'll let you decide if it's important to follow up?

Right, I sent another PR since I don't have push rights: https://github.com/quarkusio/quarkus-quickstarts/pull/646

> hum, probably unrelated but I noticed now an error on stopping the demo:

No idea what that is, but yeah it looks unrelated.

**Comment by yrodiere** [comment]
Thanks for merging this!

**Pull request merged**
