### PR TITLE
Upgrade to Hibernate Search 6.0.0.Beta9

### PR DESCRIPTION
**Pull request by yrodiere**
Needs https://github.com/quarkusio/quarkus/pull/11166 to be merged first.

**Check list**:

Your pull request:

- [x] targets the `development` branch
- [x] uses the `999-SNAPSHOT` version of Quarkus
- [x] has tests (`mvn clean test`)
- [x] works in native (`mvn clean package -Pnative`)
- [x] has native tests (`mvn clean verify -Pnative`)
- [x] makes sure the documentation must not be updated
- [x] links the documentation update pull request (if needed)
- [x] updates or creates the `README.md` file (with build and run instructions)
- [ ] For new quickstart, is located in the directory _component-quickstart_
- [ ] For new quickstart, is added to the root `pom.xml` and `README.md`

### CODE REVIEW

**Comment by yrodiere** [comment]
@gsmet Bump?

**Comment by yrodiere** [comment]
@gsmet @Sanne Could you please merge this? The build fails without these changes, since we merged the uprgade to Search 6.0.0.Beta9 in Quarkus' master branch.

**Comment by Sanne** [comment]
sure, checking it out now.. sorry I missed it.

**Review by Sanne — APPROVED** [review]

**Comment by yrodiere** [comment]
Thanks a lot!

**Pull request merged**
