### PR TITLE
Fix wrong annotation import

### PR DESCRIPTION
**Pull request by mikadev**
import javax.ws.rs.PathParam instead org.jboss.resteasy.annotations.jaxrs.PathParam

**Check list**:

Your pull request:

- [x] targets the `development` branch
- [ ] uses the `999-SNAPSHOT` version of Quarkus
- [ ] has tests (`mvn clean test`)
- [ ] works in native (`mvn clean package -Pnative`)
- [ ] has native tests (`mvn clean verify -Pnative`)
- [ ] makes sure the documentation must not be updated
- [ ] links the documentation update pull request (if needed)
- [ ] updates or creates the `README.md` file (with build and run instructions)
- [ ] For new quickstart, is located in the directory _component-quickstart_
- [ ] For new quickstart, is added to the root `pom.xml` and `README.md`

### CODE REVIEW

**Comment by cescoffier** [comment]
I believe we wanted the opposite.

@FroMage can you confirm?

**Comment by cescoffier** [comment]
BTW, this PR is targetting the `master` branch, so cannot be merged.

**Comment by mikadev** [comment]
> I believe we wanted the opposite.
> 
> @FroMage can you confirm?

You want the opposite ? i dont think

**Comment by mikadev** [comment]
> BTW, this PR is targetting the `master` branch, so cannot be merged.

Fixed

**Comment by FroMage** [comment]
Yeah, that annotation is intentional: it allows us to not duplicate the path name.

**Comment by mikadev** [comment]
Yeah maybe it just doesn't work and always give null the TU doesn't pass

**Comment by FroMage** [comment]
It definitely works and is tested. Perhaps you're running this test in your IDE and it doesn't store method parameters when it compiles the methods?

**Comment by cescoffier** [comment]
Any update on this one?

**Comment by mikadev** [comment]
For my point is a problem that is not work in IDE (intellij in my case) even you're right using maven there is no problem

**Comment by gsmet** [comment]
This PR is all screwed with version updates.

If you still want to suggest a change, please make a PR against the development branch and don't touch the versions.

I'm closing this one.

**Pull request closed without merging**
