### PR TITLE
Fix the rename from `@NamedClient` to `@GraphQLClient`

### PR DESCRIPTION
**Pull request by phillip-kruger**
Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Thanks!

**Comment by phillip-kruger** [comment]
@cescoffier the CI build failure seems unrelated, how should be proceed ?

**Comment by rsvoboda** [comment]
CI is green now, merging

**Comment by cescoffier** [comment]
Sorry, I've been swamped, thanks @rsvoboda !

**Pull request merged**
