### PR TITLE
Attempt to fix Amazon KMS tests failures

### PR DESCRIPTION
**Pull request by marcinczeczko**
**Check list**:

Your pull request:

- [x] targets the `development` branch
- [x] uses the `999-SNAPSHOT` version of Quarkus
- [x] has tests (`mvn clean test`)
- [x] works in native (`mvn clean package -Pnative`)
- [x] has native tests (`mvn clean verify -Pnative`)
- [x] makes sure the associated guide must not be updated
- [ ] links the guide update pull request (if needed)
- [ ] updates or creates the `README.md` file (with build and run instructions)
- [ ] for new quickstart, is located in the directory _component-quickstart_
- [ ] for new quickstart, is added to the root `pom.xml` and `README.md`

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by geoand** [comment]
Mind doing a follow up where you revert https://github.com/quarkusio/quarkus-quickstarts/commit/392643366317f66b7ce94243ff170412fdde56b9 ?

**Comment by marcinczeczko** [comment]
@geoand - done in #676

**Comment by gsmet** [comment]
@marcinczeczko thanks for being so reactive!

**Pull request merged**
