### PR TITLE
Use disk space reclaim script from quarkus repo

### PR DESCRIPTION
**Pull request by geoand**
Same as https://github.com/quarkusio/quarkus/pull/8963

### CODE REVIEW

**Comment by cescoffier** [comment]
This would need to be backported to the development branch, right?

**Comment by geoand** [comment]
It's not strictly necessary since the cron job uses the definition from `master`, but it would nonetheless be good to do so.

**Comment by geoand** [comment]
So if you could also cherry-pick the commit into development, that would be great (I don't seem to have the karma to do so).

**Comment by gsmet** [comment]
The master branch is rewritten regularly so yes we need it in the development branch too.

Will take care of it.

**Comment by geoand** [comment]
Thanks!

**Pull request merged**
