### PR TITLE
Replace deprecated .collectItems() with .collect()

### PR DESCRIPTION
**Pull request by DavideD**
Remove some deprecated calls from the quickstarts by using the non deprecated method.

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by gsmet** [comment]
@cescoffier CI failed in the Kafka Bare quickstart with:
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.RuntimeException: Error waiting for test resource future to finish.
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unable to start Quarkus test resource org.acme.kafka.KafkaResource@79ea5cf6
Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource org.acme.kafka.KafkaResource@79ea5cf6
Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
Caused by: java.lang.IllegalStateException: Container exited with code 126
```

**Comment by cescoffier** [comment]
@DavideD yes, an old PR has been merged, and unfortunately it was using an old version of Test Containers.
I've opened https://github.com/quarkusio/quarkus-quickstarts/pull/803.

**Comment by gsmet** [comment]
Rebased to get an unrelated CI fix.

**Comment by gsmet** [comment]
Thanks!

**Pull request merged**
