### PR TITLE
Funqy quickstarts

### PR DESCRIPTION
**Pull request by patriot1burke**

### CODE REVIEW

**Comment by patriot1burke** [comment]
Dependent on:

https://github.com/quarkusio/quarkus/pull/9344

**Comment by patriot1burke** [comment]
@gsmet Can i just merge this?

**Comment by patriot1burke** [comment]
nvm, i have to update them. :)  Some name changes to some classes.

**Comment by gsmet** [comment]
And we need CI to be green. I’ll check later why it got cancelled.

**Comment by patriot1burke** [comment]
@gsmet Ya, it keeps getting cancelled on a rerun

**Comment by gsmet** [comment]
Yeah GH actions is all weird this afternoon. Restarted the jobs manually did work.

**Comment by patriot1burke** [comment]
@gsmet Ok to merge?

**Pull request merged**
