### PR TITLE
Dependency addition needed by Flyway 10

### PR DESCRIPTION
**Pull request by rsvoboda**
Dependency addition needed by Flyway 10

Your pull request:

- [x] targets the `development` branch
- [x] uses the `999-SNAPSHOT` version of Quarkus
- [ ] has tests (`mvn clean test`)
- [ ] works in native (`mvn clean package -Pnative`)
- [ ] has integration/native tests (`mvn clean verify -Pnative`)
- [ ] makes sure the associated guide must not be updated
- [ ] links the guide update pull request (if needed)
- [ ] updates or creates the `README.md` file (with build and run instructions)
- [ ] for new quickstart, is located in the directory _component-quickstart_
- [ ] for new quickstart, is added to the root `pom.xml` and `README.md`

### CODE REVIEW

**Comment by gsmet** [comment]
We will have to wait until 3.9 is released to merge this one. Unless we backport Flyway 10 to 3.9 but people don't look that excited about the idea.

**Comment by gsmet** [comment]
Rebased as I wanted to get a full CI run for other purposes.

**Comment by rsvoboda** [comment]
@gsmet can be this merged now?

**Comment by rsvoboda** [comment]
Rebasing to pick the latest changes

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@sberyozkin @michalvavrik this `CodeFlowTest` looks concerning to me ^

**Comment by michalvavrik** [comment]
> @sberyozkin @michalvavrik this `CodeFlowTest` looks concerning to me ^

Sergey did fixes (I won't look for the PR, it's the one with the cookie resolution), tenant a is selected instead of the default one because there is a cookie session `io.quarkus.oidc.runtime.OidcAuthenticationMechanism#setTenantIdAttribute(io.vertx.ext.web.RoutingContext)`. Problem is that convention resolver should have a priority (path end withs `/default`). My best guess would be that `TENANT_ID_ATTRIBUTE` but it isn't the value of the default one because we don't set that null there @sberyozkin ? Anyway, I didn't debug it properly because Sergey has been into this in last week, he should have a look.

**Pull request merged**
