### PR TITLE
Provide a quarkus camel demo for java route

### PR DESCRIPTION
**Pull request by gnodet**

### CODE REVIEW

**Comment by davsclaus** [comment]
Can we add a bullet to the readme file in the root about this Camel quickstart like the others have

**Comment by davsclaus** [comment]
M2 has been released and are in maven central now

**Comment by gnodet** [comment]
Let me remove the commit for the repo then.

**Comment by gnodet** [comment]
> Let me remove the commit for the repo then.

This has now been fixe in quarkus master branch.

**Comment by gsmet** [comment]
@gnodet this one needs a rebase :)

**Comment by gnodet** [comment]
> @gnodet this one needs a rebase :)

Done

**Comment by davsclaus** [comment]
LGTM

Can this be merged?

**Comment by cescoffier** [comment]
@davsclaus Done!

**Comment by davsclaus** [comment]
Thanks a lot, I can now update the links in my slides for upcoming talks 👍

**Comment by cescoffier** [comment]
Actually, does it work in native?

I got:
```
[camel-java-1.0-SNAPSHOT-runner:13301]     analysis:   6,809.86 ms
Printing call tree to /Users/clement/Projects/protean/quickstarts/camel-java/target/reports/call_tree_camel-java-1.0-SNAPSHOT-runner_20190408_102450.txt
Printing list of used classes to /Users/clement/Projects/protean/quickstarts/camel-java/target/reports/used_classes_camel-java-1.0-SNAPSHOT-runner_20190408_102451.txt
Printing list of used packages to /Users/clement/Projects/protean/quickstarts/camel-java/target/reports/used_packages_camel-java-1.0-SNAPSHOT-runner_20190408_102451.txt
Error: should not reach here: Could not find field com.sun.beans.WeakCache.map on class io.quarkus.camel.core.runtime.graal.Target_com_sun_beans_WeakCache
	object com.sun.beans.WeakCache
	field java.beans.Introspector.declaredMethodCache
```

**Comment by gnodet** [comment]
It works for me:
```
gnodet•git/quarkus-quickstarts/camel-java(camel-quickstarts)» mvn clean package -Pnative                                                                                         [10:27:24]
[INFO] Scanning for projects...
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/quarkus-bom/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/quarkus-parent/999-SNAPSHOT/maven-metadata.xml
[INFO] 
[INFO] ------------------------< org.acme:camel-java >-------------------------
[INFO] Building camel-java 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: http://repo.maven.apache.org/maven2/io/quarkus/quarkus-bom/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/quarkus-camel-core/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/quarkus-camel-core-parent/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/quarkus-camel-parent/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/quarkus-core/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/quarkus-core-parent/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/quarkus-arc/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/quarkus-arc-parent/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/arc/arc/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/arc/arc-parent/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/quarkus-jaxb/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/quarkus-jaxb-parent/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/quarkus-caffeine/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/quarkus-caffeine-parent/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/quarkus-junit5/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/quarkus-test-framework/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/bootstrap/bootstrap-core/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/bootstrap/bootstrap-parent/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/quarkus-test-common/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/quarkus-core-deployment/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/quarkus-builder/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/quarkus-jsonp-deployment/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/quarkus-jsonp-parent/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/quarkus-jsonp/999-SNAPSHOT/maven-metadata.xml
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ camel-java ---
[INFO] Deleting /Users/gnodet/work/git/quarkus-quickstarts/camel-java/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ camel-java ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ camel-java ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /Users/gnodet/work/git/quarkus-quickstarts/camel-java/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ camel-java ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/gnodet/work/git/quarkus-quickstarts/camel-java/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ camel-java ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.0:test (default-test) @ camel-java ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ camel-java ---
[INFO] Building jar: /Users/gnodet/work/git/quarkus-quickstarts/camel-java/target/camel-java-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:build (default) @ camel-java ---
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/quarkus-camel-core-deployment/999-SNAPSHOT/maven-metadata.xml
Downloading from orgapachecamel-1124: https://repository.apache.org/content/repositories/orgapachecamel-1124/io/quarkus/quarkus-arc-deployment/999-SNAPSHOT/maven-metadata.xml
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Beginning quarkus augmentation
[INFO] [org.jboss.threads] JBoss Threads version 3.0.0.Alpha4
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 1321ms
[INFO] [io.quarkus.creator.phase.runnerjar.RunnerJarPhase] Building jar: /Users/gnodet/work/git/quarkus-quickstarts/camel-java/target/camel-java-1.0-SNAPSHOT-runner.jar
[INFO] 
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:native-image (default) @ camel-java ---
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] Running Quarkus native-image plugin on OpenJDK 64-Bit Server VM
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] /Library/Java/JavaVirtualMachines/graalvm-ce-1.0.0-rc14/Contents/Home/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-DCamelSimpleLRUCacheFactory=true -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar camel-java-1.0-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http -H:-SpawnIsolates -H:-JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
[camel-java-1.0-SNAPSHOT-runner:70744]    classlist:   3,555.54 ms
[camel-java-1.0-SNAPSHOT-runner:70744]        (cap):   2,251.22 ms
[camel-java-1.0-SNAPSHOT-runner:70744]        setup:   3,563.69 ms
10:28:00,903 INFO  [org.acm.cam.jav.CamelLifecycle] Initializing Camel...
10:28:00,930 INFO  [org.apa.cam.imp.con.FastTypeConverterRegistry] Type converters loaded (core: 183, classpath: 14)
10:28:00,935 INFO  [io.qua.cam.cor.run.sup.RuntimeRegistry] Creating interface org.apache.camel.spi.Language for name simple
10:28:00,935 INFO  [io.qua.cam.cor.run.sup.FastCamelContext] Binding language simple with prefix camel.language.simple
10:28:00,938 INFO  [org.acm.cam.jav.CamelLifecycle] Initialized Camel...
10:28:00,938 INFO  [org.acm.cam.jav.CamelLifecycle] Context: CamelContext(camel-1)
10:28:00,941 INFO  [io.qua.cam.cor.run.sup.FastCamelRuntime] No xml routes configured
10:28:00,966 INFO  [org.acm.cam.jav.Beans] Creating timer component from CDI
10:28:00,966 INFO  [io.qua.cam.cor.run.sup.FastCamelContext] Binding component timer with prefix camel.component.timer
10:28:00,979 INFO  [io.qua.cam.cor.run.sup.RuntimeRegistry] Creating interface org.apache.camel.spi.Language for name constant
10:28:00,979 INFO  [io.qua.cam.cor.run.sup.FastCamelContext] Binding language constant with prefix camel.language.constant
10:28:00,986 INFO  [io.qua.cam.cor.run.sup.RuntimeRegistry] Creating interface org.apache.camel.Component for name log
10:28:00,986 INFO  [io.qua.cam.cor.run.sup.FastCamelContext] Binding component log with prefix camel.component.log
[camel-java-1.0-SNAPSHOT-runner:70744]   (typeflow):  15,114.86 ms
[camel-java-1.0-SNAPSHOT-runner:70744]    (objects):  15,007.38 ms
[camel-java-1.0-SNAPSHOT-runner:70744]   (features):     473.24 ms
[camel-java-1.0-SNAPSHOT-runner:70744]     analysis:  31,652.74 ms
Printing call tree to /Users/gnodet/work/git/quarkus-quickstarts/camel-java/target/reports/call_tree_camel-java-1.0-SNAPSHOT-runner_20190408_102845.txt
Printing list of used classes to /Users/gnodet/work/git/quarkus-quickstarts/camel-java/target/reports/used_classes_camel-java-1.0-SNAPSHOT-runner_20190408_102849.txt
Printing list of used packages to /Users/gnodet/work/git/quarkus-quickstarts/camel-java/target/reports/used_packages_camel-java-1.0-SNAPSHOT-runner_20190408_102849.txt
[camel-java-1.0-SNAPSHOT-runner:70744]     universe:     869.98 ms
[camel-java-1.0-SNAPSHOT-runner:70744]      (parse):   3,101.39 ms
[camel-java-1.0-SNAPSHOT-runner:70744]     (inline):   5,020.25 ms
[camel-java-1.0-SNAPSHOT-runner:70744]    (compile):  20,410.78 ms
[camel-java-1.0-SNAPSHOT-runner:70744]      compile:  30,563.10 ms
[camel-java-1.0-SNAPSHOT-runner:70744]        image:   4,342.07 ms
[camel-java-1.0-SNAPSHOT-runner:70744]        write:   1,913.90 ms
[camel-java-1.0-SNAPSHOT-runner:70744]      [total]:  94,046.67 ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:54 min
[INFO] Finished at: 2019-04-08T10:29:27+02:00
[INFO] ------------------------------------------------------------------------
gnodet•git/quarkus-quickstarts/camel-java(camel-quickstarts)»                                                                                                                    ```

**Comment by davsclaus** [comment]
@cescoffier @gnodet actually I have also seen that native build error on my osx.

Wonder if its quakus 0.12 release vs SNAPSHOT?
But speaking of quakrus would maybe be good to get a new release out

**Comment by cescoffier** [comment]
@gnodet which version of Graal are you using?

**Comment by gnodet** [comment]
Using quarkus 999-SNAPSHOT and graalvm-ce-1.0.0-rc14

**Comment by gnodet** [comment]
Ok, it now fails after I rebuilt quarkus, so this looks like a change in quarkus causes the problem.

**Comment by davsclaus** [comment]
Ah @gnodet would be great if you could take a look and if it can be fixed by tomorrow noon as I am giving a talk in the afternoon, and would love to do a native compile demo.

**Comment by gnodet** [comment]
The culprit is https://github.com/quarkusio/quarkus/commit/c1c51b8fefd26359557b214cae8e2489d6be62a9 however, I'm not sure what the fix should be. @dmlloyd ?

**Comment by gnodet** [comment]
@davsclaus you can `git revert c1c51b8fefd26359557b214cae8e2489d6be62a9` on top of quarkus master and it works, though it seems @cescoffier just released 0.13 :-(

**Comment by davsclaus** [comment]
Thanks @gnodet with the revert it works

**Pull request merged**
