### PR TITLE
Update and sync testcontainers version, externalize version definition in security-openid ones

### PR DESCRIPTION
**Pull request by rsvoboda**
Update and sync testcontainers version, externalize version definition in security-openid ones

**Check list**:

Your pull request:

- [x] targets the `development` branch
- [x] uses the `999-SNAPSHOT` version of Quarkus
- [x] has tests (`mvn clean test`)

### CODE REVIEW

**Comment by rsvoboda** [comment]
These test failures are not related to the changes in my PR.

They are related to the https://github.com/quarkusio/quarkus/pull/13601 changes

I'm working on PR to update microprofile-metrics-quickstart

**Comment by rsvoboda** [comment]
PR for MP metrics QS update: https://github.com/quarkusio/quarkus-quickstarts/pull/730

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Rebased, let's wait for CI.

**Comment by gsmet** [comment]
There was an issue with the JDK 11 build. Looks like it stalled. It's the first time it happens so I wonder if it's related to this change.

**Comment by rsvoboda** [comment]
hmm, I had a clean run on macOS using Java 11

**Comment by rsvoboda** [comment]
@gsmet CI is green now

**Review by gsmet — APPROVED** [review]

**Pull request merged**
