### PR TITLE
Update maven-wrapper to 0.5.5

### PR DESCRIPTION
**Pull request by penehyba**
**Check list**:

Your pull request:

- [x] targets the `development` branch
- [x] uses the `999-SNAPSHOT` version of Quarkus
- [x] has tests (`mvn clean test`)
- [ ] works in native (`mvn clean package -Pnative`)
- [ ] has native tests (`mvn clean verify -Pnative`)
- [ ] makes sure the documentation must not be updated
- [ ] links the documentation update pull request (if needed)
- [ ] updates or creates the `README.md` file (with build and run instructions)
- [ ] For new quickstart, is located in the directory _component-quickstart_
- [ ] For new quickstart, is added to the root `pom.xml` and `README.md`

### CODE REVIEW

**Comment by rsvoboda** [comment]
@penehyba please describe what is the scope of this PR. How did you update these files ?
I notices permission changes too.

**Comment by penehyba** [comment]
All wrappers were updated to 0.5.5. this includes generally 5 files. I noticed there are almost random access rights 775 and 664, I decided to use 775 only for mvnw, others will be 664, this is the same setting as from bootstraping the project.
-rwxrwxr-x  1  10078 Feb  5 13:09 mvnw
-rw-rw-r--  1      6609 Feb  5 13:09 mvnw.cmd
.mvn/wrapper/
-rw-rw-r-- 1   4941 Feb  5 13:09 MavenWrapperDownloader.java
-rw-rw-r-- 1 50710 Feb  5 13:09 maven-wrapper.jar
-rw-rw-r-- 1     218 Feb  5 13:09 maven-wrapper.properties

**Comment by rsvoboda** [comment]
@gsmet / @cescoffier will you let it in ;) ?

**Comment by gsmet** [comment]
Thanks!

**Pull request merged**
