### PR TITLE
Updated webauthn code

### PR DESCRIPTION
**Pull request by FroMage**
This is the quickstarts part of https://github.com/quarkusio/quarkus/pull/44105

### CODE REVIEW

**Comment by FroMage** [comment]
Redone after many changes in webauthn4j PR

**Comment by FroMage** [comment]
Let's see if this compiles now that the PR is merged in `main`.

**Comment by geoand** [comment]
Should we merge this?

**Review by sberyozkin — APPROVED** [review]

**Comment by FroMage** [comment]
> Should we merge this? Quarkus main CI seems to be failing with it

With this PR, or without this PR?

**Pull request merged**
