### PR TITLE
Use the Infinispan Dev Service

### PR DESCRIPTION
**Pull request by cescoffier**
Requires https://github.com/quarkusio/quarkus/pull/20476

**Check-list**:

Your pull request:

- [X] targets the `development` branch
- [X] uses the `999-SNAPSHOT` version of Quarkus
- [X] has tests (`mvn clean test`)
- [X] works in native (`mvn clean package -Pnative`)
- [X] has native tests (`mvn clean verify -Pnative`)
- [X] makes sure the associated guide must not be updated
- [X] links the guide update pull request (if needed)
- [X] updates or creates the `README.md` file (with build and run instructions)
- [X] for new quickstart, is located in the directory _component-quickstart_
- [X] for new quickstart, is added to the root `pom.xml` and `README.md`

### CODE REVIEW

**Review by karesti — APPROVED** [review]

**Comment by cescoffier** [comment]
I rebased the PR.

**Comment by karesti** [comment]
@cescoffier do we want to leave the test resource class in the source ?

**Review by karesti — APPROVED** [review]

**Comment by cescoffier** [comment]
@karesti no need for the test resource anymore.

**Comment by karesti** [comment]
@cescoffier I was under the impression we had the container resource file still in the source code! perfect!!

**Pull request merged**
