### PR TITLE
Fix s2i scripts

### PR DESCRIPTION
**Pull request by geoand**
These broke when we moved to fast-jar by default

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by geoand** [comment]
This was reported as bug from the Openshift folks BTW.

**Comment by rsvoboda** [comment]
@geoand I think you could backport this fix into `main`, this way the "OCP embeded quickstart" would work once the fix gets merged

**Comment by geoand** [comment]
@rsvoboda yeah, if we want the fix to be available now, it likely need to be merged into `main`

**Comment by geoand** [comment]
@rsvoboda I pushed the change to `main` as well

**Pull request merged**
