### PR TITLE
OptaPlanner quickstart: UI demo improvements

### PR DESCRIPTION
**Pull request by ge0ffrey**
Mainly some JS cleanup and making the UI easier to read. Also add a constraint so the demo really does improve life for students too.

### CODE REVIEW

**Comment by ge0ffrey** [comment]
Now targeted at development branch :)

**Comment by ge0ffrey** [comment]
@ia3andy Can we get poke CI to try it again? It's probably a random failure. I'd like to get this merged.

**Comment by ia3andy** [comment]
@ge0ffrey I think I've found a bug when deleting a room:
```
Caused by: org.h2.jdbc.JdbcSQLException: Intégrité référentielle violation de contrainte: "FKSQ105PP66NWQ8NV9C5009BM91: PUBLIC.LESSON FOREIGN KEY(ROOM_ID) REFERENCES PUBLIC.ROOM(ID) (11)"
Referential integrity constraint violation: "FKSQ105PP66NWQ8NV9C5009BM91: PUBLIC.LESSON FOREIGN KEY(ROOM_ID) REFERENCES PUBLIC.ROOM(ID) (11)"; SQL statement:
delete from Room where id=? [23503-197]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:386)
        at org.h2.constraint.ConstraintReferential.checkRowRefTable(ConstraintReferential.java:403)
        at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:278)
        at org.h2.table.Table.fireConstraints(Table.java:995)
        at org.h2.table.Table.fireAfterRow(Table.java:1013)
        at org.h2.command.dml.Delete.update(Delete.java:108)
        at org.h2.command.CommandContainer.update(CommandContainer.java:102)
        at org.h2.command.Command.executeUpdate(Command.java:261)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
        at io.agroal.pool.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:85)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
        ... 72 more

```

**Comment by ge0ffrey** [comment]
> @ge0ffrey I think I've found a bug when deleting a room:
> 
> ```
> Caused by: org.h2.jdbc.JdbcSQLException: Intégrité référentielle violation de contrainte: "FKSQ105PP66NWQ8NV9C5009BM91: PUBLIC.LESSON FOREIGN KEY(ROOM_ID) REFERENCES PUBLIC.ROOM(ID) (11)"
> Referential integrity constraint violation: "FKSQ105PP66NWQ8NV9C5009BM91: PUBLIC.LESSON FOREIGN KEY(ROOM_ID) REFERENCES PUBLIC.ROOM(ID) (11)"; SQL statement:
> delete from Room where id=? [23503-197]
>         at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
>         at org.h2.message.DbException.get(DbException.java:179)
>         at org.h2.message.DbException.get(DbException.java:155)
>         at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:386)
>         at org.h2.constraint.ConstraintReferential.checkRowRefTable(ConstraintReferential.java:403)
>         at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:278)
>         at org.h2.table.Table.fireConstraints(Table.java:995)
>         at org.h2.table.Table.fireAfterRow(Table.java:1013)
>         at org.h2.command.dml.Delete.update(Delete.java:108)
>         at org.h2.command.CommandContainer.update(CommandContainer.java:102)
>         at org.h2.command.Command.executeUpdate(Command.java:261)
>         at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
>         at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
>         at io.agroal.pool.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:85)
>         at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
>         ... 72 more
> ```

@ia3andy That's a known issue: when you try to delete a room that is in use, hibernate throws an foreign key violation and the UI just properly shows any error to avoid missing critical bugs by sweeping them under the carpet. But the message is indeed unclear, something we want to improve to motivate why that room can't be deleted.
In any case, it's not a regression, that is there already on master.

**Comment by gsmet** [comment]
@ia3andy I let you drive this puppy home?

**Comment by ge0ffrey** [comment]
Thanks Andy!

**Pull request merged**
