### PR TITLE
Remove unused imports and commented out annotations

### PR DESCRIPTION
**Pull request by rsynek**

### CODE REVIEW

**Comment by ge0ffrey** [comment]
Thanks Radovan - I hadn't seen this PR. I think it's a subset (=duplication) of the changes I did later in https://github.com/quarkusio/quarkus-quickstarts/pull/484

**Comment by ge0ffrey** [comment]
@rsynek Would you mind closing this PR if #484 duplicates it, so it's easier for the quarkus team to know what the merge. My apologies for not seeing this PR (I wouldn't have made mine or build it on top of this one at least).

**Comment by rsynek** [comment]
@ge0ffrey no problem at all. After quickly checking the changed files, your PR https://github.com/quarkusio/quarkus-quickstarts/pull/484 contains only a subset of removes of unused imports.

**Comment by gsmet** [comment]
This PR is now conflicting and needs a rebase.

**Comment by rsynek** [comment]
Closing as the cosmetic changes were already addressed in https://github.com/quarkusio/quarkus-quickstarts/pull/484.

**Pull request closed without merging**
