### PR TITLE
Set the version of keycloak to 7.0.1

### PR DESCRIPTION
**Pull request by cescoffier**
This PR sets the Keycloak version to 7.0.1 to avoid the issue we have with 8.0.0. 
It needs to be cherry-picked to the 1.0 branch and master branch. 

**Checklist**:

Your pull request:

- [X] targets the `development` branch
- [X] uses the `999-SNAPSHOT` version of Quarkus
- [X] updates or creates the `README.md` file (with build and run instructions)

### CODE REVIEW

**Comment by cescoffier** [comment]
Thanks @machi1990 !

**Comment by cescoffier** [comment]
Going to cherry-pick for 1.0 and master.

**Comment by cescoffier** [comment]
All done! Back on track.

**Comment by rsvoboda** [comment]
@cescoffier 

>  to avoid the issue we have with 8.0.0. 

Looked at https://github.com/quarkusio/quarkus/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+keycloak but didn't find any issue for this

I was playing with Keycloak 8 and hit issues in native mode so I startedted to look around ...

**Comment by rsvoboda** [comment]
For the record, I see:
```
Caused by: java.lang.NullPointerException
	at java.net.URI$Parser.parse(URI.java:3042)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:66)
	at org.keycloak.adapters.rotation.JWKPublicKeyLocator.sendRequest(JWKPublicKeyLocator.java:97)
	at org.keycloak.adapters.rotation.JWKPublicKeyLocator.getPublicKey(JWKPublicKeyLocator.java:63)
	at org.keycloak.adapters.rotation.AdapterTokenVerifier.getPublicKey(AdapterTokenVerifier.java:121)
	at org.keycloak.adapters.rotation.AdapterTokenVerifier.createVerifier(AdapterTokenVerifier.java:111)
	at org.keycloak.adapters.rotation.AdapterTokenVerifier.verifyToken(AdapterTokenVerifier.java:47)
	at org.keycloak.adapters.authorization.KeycloakAdapterPolicyEnforcer.requestAuthorizationToken(KeycloakAdapterPolicyEnforcer.java:172)
	... 15 more
```

**Pull request merged**
