### PR TITLE
create HR example using StatelessSession

### PR DESCRIPTION
**Pull request by gavinking**
A new example that shows off `StatelessSession`.

### CODE REVIEW

**Comment by gsmet** [comment]
@DavideD could you have look?

**Comment by DavideD** [comment]
Sure

**Comment by DavideD** [comment]
Looks great but  maybe we could add a line to explain when one can use the `StatelessSession` instead of the regular one.
Otherwise I feel it might confuse people having two examples doing pretty much the same thing.

**Comment by gavinking** [comment]
Why has this four-month old PR not been merged?

**Comment by DavideD** [comment]
By the way, why is this a separate quickstart? Couldn't we add it in the one we already have?

**Pull request merged**
