### PR TITLE
Feature/microprofile graphql quickstart

### PR DESCRIPTION
**Pull request by cemnura**
**Check list**:

Your pull request:

- [x] targets the `development` branch
- [x] uses the `999-SNAPSHOT` version of Quarkus
- [x] has tests (`mvn clean test`)
- [x] works in native (`mvn clean package -Pnative`)
- [x] has native tests (`mvn clean verify -Pnative`)
- [ ] makes sure the documentation must not be updated
- [x] links the documentation update pull request (if needed)
- [ ] updates or creates the `README.md` file (with build and run instructions)
- [ ] For new quickstart, is located in the directory _component-quickstart_
- [x] For new quickstart, is added to the root `pom.xml` and `README.md`

### CODE REVIEW

**Comment by cemnura** [comment]
https://github.com/quarkusio/quarkus/pull/8967

**Comment by cemnura** [comment]
Added test code.

**Comment by cemnura** [comment]
Would I need to combine the commits into one?

**Comment by cemnura** [comment]
Squashed commits. 👍

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request merged**
