### PR TITLE
Fix Elytron-JDBC Quickstart in native mode

### PR DESCRIPTION
**Pull request by danielpetisme**
Here you have an initial version @cescoffier

### CODE REVIEW

**Comment by gsmet** [comment]
Could you squash everything into one commit, please?

**Comment by gsmet** [comment]
I tried to run the tests with `mvn clean install` and I end up with:
```
[INFO] Running org.acme.elytron.security.jdbc.JdbcSecurityRealmTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 31.284 s <<< FAILURE! - in org.acme.elytron.security.jdbc.JdbcSecurityRealmTest
[ERROR] org.acme.elytron.security.jdbc.JdbcSecurityRealmTest  Time elapsed: 31.282 s  <<< ERROR!
java.lang.ExceptionInInitializerError
	at org.acme.elytron.security.jdbc.JdbcSecurityRealmTest.<clinit>(JdbcSecurityRealmTest.java:25)
```
It waits for 30s so it looks like a connection timeout. But I don't see any other failure.

**Comment by danielpetisme** [comment]
Don't like to say that but...  works on my machine
Running only the concerned tests
```
[INFO] --- maven-surefire-plugin:2.22.0:test (default-test) @ elytron-security-jdbc ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.acme.elytron.security.jdbc.JdbcSecurityRealmTest
        ℹ︎ Checking the system...
        ✔ Docker version should be at least 1.6.0
        ✔ Docker environment should have more than 2GB free disk space
2019-10-23 22:54:23,589 INFO  [org.tes.doc.DockerClientProviderStrategy] (main) Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
2019-10-23 22:54:23,627 INFO  [org.tes.doc.DockerClientProviderStrategy] (main) Will use 'okhttp' transport
2019-10-23 22:54:24,169 INFO  [org.tes.doc.UnixSocketClientProviderStrategy] (main) Accessing docker with local Unix socket
2019-10-23 22:54:24,169 INFO  [org.tes.doc.DockerClientProviderStrategy] (main) Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
2019-10-23 22:54:24,171 INFO  [org.tes.DockerClientFactory] (main) Docker host IP address is localhost
2019-10-23 22:54:24,338 INFO  [org.tes.DockerClientFactory] (main) Connected to docker:
  Server Version: 19.03.2
  API Version: 1.40
  Operating System: Docker Desktop
  Total Memory: 1998 MB
2019-10-23 22:54:24,942 INFO  [org.tes.uti.RegistryAuthLocator] (main) Credential helper/store (docker-credential-desktop) does not have credentials for quay.io
2019-10-23 22:54:25,838 INFO  [org.tes.DockerClientFactory] (main) Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
2019-10-23 22:54:26,185 INFO  [🐳 .6.12]] (main) Creating container for image: postgres:9.6.12
2019-10-23 22:54:26,233 INFO  [org.tes.uti.RegistryAuthLocator] (main) Credential helper/store (docker-credential-desktop) does not have credentials for index.docker.io
2019-10-23 22:54:26,419 INFO  [🐳 .6.12]] (main) Starting container with ID: e7a034bf0b411501f46d5a8519d8e8d27f05fc72e382128f5c559a38f0515f09
2019-10-23 22:54:27,045 INFO  [🐳 .6.12]] (main) Container postgres:9.6.12 is starting: e7a034bf0b411501f46d5a8519d8e8d27f05fc72e382128f5c559a38f0515f09
2019-10-23 22:54:31,644 INFO  [🐳 .6.12]] (main) Container postgres:9.6.12 started
2019-10-23 22:54:31,649 INFO  [org.tes.ext.ScriptUtils] (main) Executing database script from test_user.sql
2019-10-23 22:54:31,748 INFO  [org.tes.ext.ScriptUtils] (main) Executed database script from test_user.sql in 99 ms.
2019-10-23 22:54:33,235 INFO  [io.qua.dep.QuarkusAugmentor] (main) Beginning quarkus augmentation
2019-10-23 22:54:34,180 INFO  [io.qua.resteasy] (build-3) Resteasy running without servlet container.
2019-10-23 22:54:34,180 INFO  [io.qua.resteasy] (build-3) - Add quarkus-undertow to run Resteasy within a servlet container
2019-10-23 22:54:34,273 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 1038ms
2019-10-23 22:54:34,955 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 0.680s. Listening on: http://0.0.0.0:8081
2019-10-23 22:54:34,955 INFO  [io.quarkus] (main) Profile test activated.
2019-10-23 22:54:34,955 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, jdbc-postgresql, narayana-jta, resteasy, security, security-jdbc]
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.307 s - in org.acme.elytron.security.jdbc.JdbcSecurityRealmTest
2019-10-23 22:54:36,864 INFO  [io.quarkus] (main) Quarkus stopped in 0.033s
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
```

Installing from the quickstarts folder 
```
$ mvn clean install
....
[INFO] Reactor Summary for quickstart-projects 1.0-SNAPSHOT:
[INFO]
[INFO] application-configuration .......................... SUCCESS [  7.977 s]
[INFO] application-lifecycle-events ....................... SUCCESS [  4.886 s]
[INFO] getting-started .................................... SUCCESS [  4.981 s]
[INFO] getting-started-async .............................. SUCCESS [  4.735 s]
[INFO] hibernate-orm-resteasy ............................. SUCCESS [ 12.925 s]
[INFO] hibernate-orm-panache-resteasy ..................... SUCCESS [ 11.024 s]
[INFO] infinispan-client .................................. SUCCESS [  1.258 s]
[INFO] validation ......................................... SUCCESS [  6.664 s]
[INFO] scheduling-periodic-tasks .......................... SUCCESS [  5.920 s]
[INFO] using-websockets ................................... SUCCESS [  4.731 s]
[INFO] using-openapi-swaggerui ............................ SUCCESS [  7.022 s]
[INFO] using-opentracing .................................. SUCCESS [  6.684 s]
[INFO] using-spring-di .................................... SUCCESS [  5.616 s]
[INFO] using-spring-web ................................... SUCCESS [  7.670 s]
[INFO] using-spring-data-jpa .............................. SUCCESS [ 32.109 s]
[INFO] using-jwt-rbac ..................................... SUCCESS [  7.572 s]
[INFO] rest-client ........................................ SUCCESS [  9.840 s]
[INFO] rest-client-multipart .............................. SUCCESS [  6.030 s]
[INFO] kafka-quickstart ................................... SUCCESS [  6.456 s]
[INFO] kafka-streams-quickstart ........................... SUCCESS [  0.007 s]
[INFO] kafka-streams-quickstart-producer .................. SUCCESS [  0.747 s]
[INFO] kafka-streams-quickstart-aggregator ................ SUCCESS [  0.881 s]
[INFO] amqp-quickstart .................................... SUCCESS [  0.877 s]
[INFO] rest-json .......................................... SUCCESS [  6.481 s]
[INFO] getting-started-knative ............................ SUCCESS [  5.145 s]
[INFO] getting-started-testing ............................ SUCCESS [  5.840 s]
[INFO] mqtt-quickstart .................................... SUCCESS [ 27.554 s]
[INFO] microprofile-fault-tolerance ....................... SUCCESS [  7.978 s]
[INFO] microprofile-health ................................ SUCCESS [  6.545 s]
[INFO] microprofile-metrics ............................... SUCCESS [  6.574 s]
[INFO] using-vertx ........................................ SUCCESS [ 10.893 s]
[INFO] using-openid-connect ............................... SUCCESS [  0.764 s]
[INFO] hibernate-search-elasticsearch ..................... SUCCESS [02:44 min]
[INFO] using-kogito ....................................... SUCCESS [ 13.558 s]
[INFO] mongo-client ....................................... SUCCESS [  0.927 s]
[INFO] mongodb-panache .................................... SUCCESS [  0.950 s]
[INFO] neo4j-quickstart ................................... SUCCESS [  0.738 s]
[INFO] dynamodb-client .................................... SUCCESS [  1.126 s]
[INFO] using-oauth2-rbac .................................. SUCCESS [  0.755 s]
[INFO] artemis-jms ........................................ SUCCESS [  7.794 s]
[INFO] using-reactive-routes .............................. SUCCESS [  4.840 s]
[INFO] stm-quarkus-quickstart ............................. SUCCESS [  5.646 s]
[INFO] elytron-security-jdbc .............................. SUCCESS [ 15.020 s]
[INFO] apache-tika ........................................ SUCCESS [  8.360 s]
[INFO] quickstart-projects ................................ SUCCESS [  0.005 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:39 min
[INFO] Finished at: 2019-10-23T23:04:34+02:00
[INFO] ------------------------------------------------------------------------
```

The CI is green so my guess is an issue on your local setup. Could you activate debug logs and share them please?

**Comment by gsmet** [comment]
Well, there is no CI so it doesn't count :)

**Comment by gsmet** [comment]
@cescoffier can you have a look at this one? I'm totally unable to get test containers to work on my laptop. I have the same issue with the Vault ITs.

**Comment by cescoffier** [comment]
I'm on it. As there are a few things on it, I may force push some changes.

**Comment by cescoffier** [comment]
Superseded by #341

**Pull request closed without merging**
