### PR TITLE
Redis Streams QuickStart guide

### PR DESCRIPTION
**Pull request by pliakas**
Inspired by kafka-streams-quickstart guide, I have implemented an example how to use redis-streams with quarkus. 

There is a limitation regarding the native part, where the tests is not able to run, due to the use of `@Inject` annotation. 

**Check list**:

Your pull request:

- [ x ] targets the `development` branch
- [ x ] uses the `999-SNAPSHOT` version of Quarkus
- [ x ] has tests (`mvn clean test`)
- [  - ] works in native (`mvn clean package -Pnative`)
- [ - ] has integration/native tests (`mvn clean verify -Pnative`)
- [ - ] makes sure the associated guide must not be updated
- [ - ] links the guide update pull request (if needed)
- [ x ] updates or creates the `README.md` file (with build and run instructions)
- [ x ] for new quickstart, is located in the directory _component-quickstart_
- [ x ] for new quickstart, is added to the root `pom.xml` and `README.md`

### CODE REVIEW

**Comment by cescoffier** [comment]
Could you rebase? That's way too much for a single PR (528 changed files :-D)

**Comment by pliakas** [comment]
> Could you rebase? That's way too much for a single PR (528 changed files :-D)

I think I have messed up my fork and PR. I will close this PR, clean up my fork - branch and re-open it. 

I am sorry for this inconvenience

**Comment by gsmet** [comment]
@pliakas no worries. Be careful, this repository is a bit weird: the default branch is `main` but the actual branch for which we want the PR is the `development` branch. So make sure you branch your work from the `development` branch and create your PR against the `development` branch too.

**Comment by pliakas** [comment]
> @pliakas no worries. Be careful, this repository is a bit weird: the default branch is `main` but the actual branch for which we want the PR is the `development` branch. So make sure you branch your work from the `development` branch and create your PR against the `development` branch too.

Thanks for the hint, I realized in the "hard" way .. :) The new PR is: #1335

**Pull request closed without merging**
