### PR TITLE
Add Security LDAP QuickStart

### PR DESCRIPTION
**Pull request by michalvavrik**
Adds QuickStart for https://quarkus.io/guides/security-ldap, should close https://github.com/quarkusio/quarkus/issues/25989. Associated guide must be updated (will do, it's just `application.properties`) as I've chosen different BaseDN, principal and password so that I don't have to provide my own implementation of `LdapServerTestResource` - it's not a problem, but would add unnecessary complexity (one new Java class and LDIF resource). I think guide update makes sense anyway to address [assumptions that are not described the guide](https://github.com/quarkusio/quarkus/issues/10049).

Your pull request:

- [x] targets the `development` branch
- [x] uses the `999-SNAPSHOT` version of Quarkus
- [x] has tests (`mvn clean test`)
- [x] works in native (`mvn clean package -Pnative`)
- [x] has integration/native tests (`mvn clean verify -Pnative`)
- [ ] makes sure the associated guide must not be updated
- [x] links the guide update pull request (if needed)
- [x] updates or creates the `README.md` file (with build and run instructions)
- [x] for new quickstart, is located in the directory _component-quickstart_
- [x] for new quickstart, is added to the root `pom.xml` and `README.md`

### CODE REVIEW

**Comment by michalvavrik** [comment]
cc @gsmet @sberyozkin

**Comment by sberyozkin** [comment]
@michalvavrik Thanks a million for fixing the long pending issue, cheers

**Review by sberyozkin — APPROVED** [review]
@michalvavrik Please follow next week with the quickstart doc sync

**Comment by michalvavrik** [comment]
Will do.

**Pull request merged**
