### PR TITLE
Update FruitResource.java

### PR DESCRIPTION
**Pull request by blue61**
added GET commands to actually Create, Update or Delete Entities, as the other HTTP Verbs are often unaccessible in browsers.
GET /fruits/-/name    creates a new entity
GET /fruits/id/name   updates the entity with the given id to have the given name
GET /fruits/id/-          deletes the entity with the given id

**Please make sure that your pull request is targeting the `development` branch.**

### CODE REVIEW

**Comment by cescoffier** [comment]
Not sure about that one.

@FroMage WDYT?

**Comment by FroMage** [comment]
> the other HTTP Verbs are often unaccessible in browsers

Are you sure? XmlHttpRequest supports it for ever, I think.

`GET` requests should be idempotent and should be cacheable and never ever modify data, so I think this is really not the right way to do REST.

**Comment by gsmet** [comment]
I haven’t merged that one because I thought it’s better to have the demo as simple as possible and not add too many things. 

It’s just my preference though.

**Comment by cescoffier** [comment]
I believe we should not merge. It does not follow the REST good practices,
and it complexifies the QuickStart.

**Pull request closed without merging**
