### PR TITLE
Upgrade stork k8s quickstart

### PR DESCRIPTION
**Pull request by aureamunoz**
**Check list**:

Your pull request:

- [ ] targets the `development` branch
- [ ] uses the `999-SNAPSHOT` version of Quarkus
- [ ] has tests (`mvn clean test`)
- [ ] works in native (`mvn clean package -Pnative`)
- [ ] has integration/native tests (`mvn clean verify -Pnative`)
- [ ] makes sure the associated guide must not be updated
- [ ] links the guide update pull request (if needed)
- [ ] updates or creates the `README.md` file (with build and run instructions)
- [ ] for new quickstart, is located in the directory _component-quickstart_
- [ ] for new quickstart, is added to the root `pom.xml` and `README.md`

### CODE REVIEW

**Comment by aureamunoz** [comment]
cc @cescoffier

**Comment by cescoffier** [comment]
@aureamunoz Can you rebase, and make sure you target the development branch?

**Comment by aureamunoz** [comment]
I can't, you had already merged the initial PR
Captura de pantalla 2023-10-23 a las 10 16 40

**Comment by aureamunoz** [comment]
This PR is duplicated of #1338

**Pull request closed without merging**
