### PR TITLE
Workaround for failures, when running with podman

### PR DESCRIPTION
**Pull request by fedinskiy**
Call to method `withClasspathResourceMapping` with RO and without
Selinux leads to files being copied *after* the start-up of contanier.

**Check list**:

Your pull request:

- [ ] targets the `development` branch
- [x] uses the `999-SNAPSHOT` version of Quarkus
- [x] has tests (`mvn clean test`)
- [x] works in native (`mvn clean package -Pnative`)
- [x] makes sure the associated guide must not be updated
- [ ] links the guide update pull request (if needed)
- [ ] updates or creates the `README.md` file (with build and run instructions)

### CODE REVIEW

**Comment by sberyozkin** [comment]
@fedinskiy It needs to be done against `development`, sorry I did not notice it

**Comment by rsvoboda** [comment]
Plus there is https://github.com/quarkusio/quarkus-quickstarts/tree/2.7 branch now

**Comment by rsvoboda** [comment]
Out of curiosity, `KeycloakDevServicesProcessor` from Quarkus main codebase doesn't need similar adjustment?

https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java#L422-L428

**Comment by fedinskiy** [comment]
Replaced with https://github.com/quarkusio/quarkus-quickstarts/pull/1092

**Pull request closed without merging**
