### PR TITLE
Add Hibernate ORM Rest Data with Panache quickstart

### PR DESCRIPTION
**Pull request by Sgitario**
The Quarkus Hibernate ORM Rest Data with Panache was promoted to Stable in https://github.com/quarkusio/quarkus/pull/28569, so let's add a quickstart for it.

This quickstart is based on the code in the guide: https://quarkus.io/guides/rest-data-panache

Relates https://github.com/quarkusio/quarkus/issues/29555

**Check list**:

Your pull request:

- [x] targets the `development` branch
- [x] uses the `999-SNAPSHOT` version of Quarkus
- [x] has tests (`mvn clean test`)
- [x] works in native (`mvn clean package -Pnative`)
- [x] has integration/native tests (`mvn clean verify -Pnative`)
- [x] makes sure the associated guide must not be updated
- [x] links the guide update pull request (if needed)
- [x] updates or creates the `README.md` file (with build and run instructions)
- [x] for new quickstart, is located in the directory _component-quickstart_
- [x] for new quickstart, is added to the root `pom.xml` and `README.md`

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by fedinskiy** [comment]
@Sgitario  thank you! In your opinion, is it possible to backport this change to 2.13?

CC @gsmet

**Comment by geoand** [comment]
Backport a quickstart change?

**Comment by fedinskiy** [comment]
@geoand yes, to have it in 2.13 branch

**Comment by fedinskiy** [comment]
It depends on your definition of "use", but we verify compatibility of patch(aka ".z") Quarkus releases with them :)

**Comment by Sgitario** [comment]
PR to include the quickstart into 2.13 https://github.com/quarkusio/quarkus-quickstarts/pull/1235

**Pull request merged**
