### PR TITLE
Rename microprofile-messaging-mqtt to be in sync with artifactId mqtt-quickstart

### PR DESCRIPTION
**Pull request by rsvoboda**
Rename microprofile-messaging-mqtt to be in sync with artifactId mqtt-quickstart

Also there is amqp-quickstart and kafka-quickstart, so having mqtt-quickstart aligns with that.

Note: microprofile-messaging-mqtt  keyword is not mentioned in Quarkus docs, so no need to update anything there or on the site.

### CODE REVIEW

**Comment by rsvoboda** [comment]
My main motivation was to be aligned with other messaging related quickstarts - amqp-quickstart and kafka-quickstart.

For microprofile-messaging-mqtt I didn't see direct connection between mqtt and microprofile, had to look at readme :).
It uses MicroProfile Reactive Messaging so wouldn't be `microprofile-reactive-messaging-mqtt` better name?

**Comment by rsvoboda** [comment]
https://github.com/quarkusio/quarkus-quickstarts/tree/master/amqp-quickstart#quarkus-amqp-10-quickstart uses MicroProfile Reactive Messaging too, so the name should be adjusted too :) ?

**Comment by rsvoboda** [comment]
crap, https://github.com/quarkusio/quarkus-quickstarts/tree/master/kafka-quickstart#quarkus-kafka-quickstart uses it too ... 😱

**Comment by gsmet** [comment]
Closing as I renamed all the quickstarts.

**Pull request closed without merging**
